name = "foragd-reverse-proxy"
main = "index.ts"
compatibility_date = "2024-01-01"

[vars]
FORAGD_REVERSEPROXY_PORT = 7000
FORAGD_REVERSEPROXY_HOST = "0.0.0.0"
FORAGD_REVERSEPROXY_READTIMEOUT = "120s"
FORAGD_REVERSEPROXY_WRITETIMEOUT = "30s"
FORAGD_REVERSEPROXY_IDLETIMEOUT = "900s"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[[containers]]
max_instances = 10
class_name = "ReverseProxy"
image = "../../reverseproxy.Dockerfile"

[[durable_objects.bindings]]
name = "FORAGD_REVERSEPROXY"
class_name = "ReverseProxy"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ReverseProxy"]
