# Copyright 2024 Joshua Rich <joshua.rich@gmail.com>.
# SPDX-License-Identifier: 	AGPL-3.0-or-later
openapi: '3.1.0'
info:
  version: 1.0.0
  title: Common Models
  description: Common objects and fields.
components:
  schemas:
    # Common Fields.
    Timestamp:
      description: is when the document was created.
      x-go-type: 'time.Time'
      x-oapi-codegen-extra-tags:
        json: "@timestamp"
        validate: "required"
    CreatedAt:
      description: records when the object was created in the database.
      x-go-type: 'time.Time'
      x-oapi-codegen-extra-tags:
        json: 'created_at,omitempty'
    UpdatedAt:
      description: records when the object was last updated in the database.
      x-go-type: 'time.Time'
      x-oapi-codegen-extra-tags:
        json: 'updated_at,omitempty'
    MarkedRead:
      description: records when the object was last marked read.
      x-go-type: 'time.Time'
      x-oapi-codegen-extra-tags:
        json: 'marked_read,omitempty'
    DeletedAt:
      description: records when the object was deleted.
      x-go-type: 'time.Time'
      x-oapi-codegen-extra-tags:
        json: 'deleted_at,omitempty'
    URL: &URL
      description: is a URL.
      type: string
      x-go-name: 'URL'
      x-oapi-codegen-extra-tags:
        validate: 'required,url'
        json: 'url'
        form: 'url'
    State:
      description: >
        Tracks the state of an object.
      type: string
      enum: ["read","unread","saved"]
      default: "unread"
      x-oapi-codegen-extra-tags:
        json: 'state'
        form: 'state'
    HTMLString:
      description: is a string that can contain HTML.
      type: string
      x-go-type-skip-optional-pointer: true
    FeedID:
      description: is the unique ID of a feed.
      type: string
      x-oapi-codegen-extra-tags:
        validate: 'required'
        json: 'feed_id'
        form: 'feed_id'
    FeedURL:
      description: The canonical feed URL.
      type: string
      x-go-name: 'FeedURL'
      x-oapi-codegen-extra-tags:
        json: 'feedLink'
        validate: 'required,url'
    ItemID:
      description: is the unique ID of an item.
      type: string
      x-oapi-codegen-extra-tags:
        validate: 'required'
        json: 'item_id'
        form: 'item_id'
    ItemURL:
      description: A URL to view the original item.
      type: string
      x-go-name: 'ItemURL'
      x-oapi-codegen-extra-tags:
        json: 'link'
        validate: 'required,url'
    UserItemProperties:
      description: Tracks user-specific properties of an item.
      type: object
      properties:
        State:
          $ref: '#/components/schemas/State'
      x-oapi-codegen-extra-tags:
        json: '-'
    UserFeedProperties:
      description: Tracks user-specific properties of a feed.
      type: object
      properties:
        unread_count:
          type: integer
          minimum: 0
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        nickname:
          type: string
    UserID:
      description: is the unique ID of a user.
      type: string
      x-oapi-codegen-extra-tags:
        validate: 'required'
        json: 'user_id'
        form: 'user_id'
    SchedulerID:
      description: is the unique ID of a job scheduler instance.
      type: string
      x-oapi-codegen-extra-tags:
        validate: 'required'
        json: 'scheduler_id'
    Category:
      description: is a single category.
      type: string
      x-oapi-codegen-extra-tags:
        json: 'category'
        form: 'category'
    # Metadata Objects.
    MetadataFeed:
      description: contains common/metadata fields for feeds and items.
      type: object
      required:
        - title
        - description
      properties:
        title:
          $ref: '#/components/schemas/HTMLString'
        description:
          $ref: '#/components/schemas/HTMLString'
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
          x-go-type-skip-optional-pointer: true
        image:
          x-go-type: '*gofeed.Image'
          x-go-type-import:
            path: github.com/mmcdole/gofeed
          x-go-type-skip-optional-pointer: true
        authors:
          x-go-type: '[]*gofeed.Person'
          x-go-type-import:
            path: github.com/mmcdole/gofeed
          x-go-type-skip-optional-pointer: true
        published:
          x-oapi-codegen-extra-tags:
            json: 'publishedParsed'
          x-go-type: 'time.Time'
          x-go-type-skip-optional-pointer: true
        updated:
          x-oapi-codegen-extra-tags:
            json: 'updatedParsed'
          x-go-type: 'time.Time'
          x-go-type-skip-optional-pointer: true
    MetadataDB:
      description: contains common (metadata) fields for database objects.
      type: object
      required:
        - created_at
      properties:
        CreatedAt:
          $ref: '#/components/schemas/CreatedAt'
        UpdatedAt:
          $ref: '#/components/schemas/UpdatedAt'
    ItemState:
      description: Contains fields to track an individual item's state.
      type: object
      required:
        - State
        - UpdatedAt
      properties:
        UpdatedAt:
          $ref: '#/components/schemas/UpdatedAt'
        State:
          $ref: '#/components/schemas/State'
    # Objects.
    SubscriptionState:
      description: Contains fields to rack a subscription state.
      type: object
      required:
        - CreatedAt
      properties:
        CreatedAt:
          $ref: '#/components/schemas/CreatedAt'
        UpdatedAt:
          $ref: '#/components/schemas/UpdatedAt'
        MarkedRead:
          $ref: '#/components/schemas/MarkedRead'
        name:
          description: >
            is a friendly name or nickname for the feed given by the user.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'name'
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
          x-go-type-skip-optional-pointer: true
    User:
      description: is a user of the application.
      type: object
      allOf:
        - $ref: '#/components/schemas/MetadataDB'
        - type: object
          required:
            - ID
            - MaxHistory
          properties:
            ID:
              $ref: '#/components/schemas/UserID'
            max_history:
              description: >
                Represents the maximum time-frame over which the user
                can view items.
              type: string
            feed_item_states:
              description: Tracks state of inidividual items per feed.
              type: object
              additionalProperties:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/ItemState'
              x-go-type-skip-optional-pointer: true
            subscriptions:
              description: is the list of user subscriptions.
              type: object
              additionalProperties:
                $ref: '#/components/schemas/SubscriptionState'
              x-go-type-skip-optional-pointer: true
    APIFeed:
      description: represents a feed object for API endpoints.
      type: object
      required:
        - title
        - description
        - URL
        - ID
      allOf:
        - $ref: '#/components/schemas/MetadataFeed'
        - $ref: '#/components/schemas/MetadataDB'
        - type: object
          required:
            - ID
            - URL
          properties:
            ID:
              $ref: '#/components/schemas/FeedID'
            URL:
              $ref: '#/components/schemas/FeedURL'
            language:
              type: string
              x-go-type-skip-optional-pointer: true
            copyright:
              type: string
              x-go-type-skip-optional-pointer: true
            generator:
              type: string
              x-go-type-skip-optional-pointer: true
            feed_type:
              type: string
              x-oapi-codegen-extra-tags:
                json: 'feedType'
              x-go-type-skip-optional-pointer: true
            feed_version:
              type: string
              x-oapi-codegen-extra-tags:
                json: 'feedVersion'
              x-go-type-skip-optional-pointer: true
            UserProperties:
              $ref: '#/components/schemas/UserFeedProperties'
    APIFeedState:
      description: tracks the state of a feed.
      type: object
      required:
        - ID
        - URL
      properties:
        ID:
          $ref: '#/components/schemas/FeedID'
        URL:
          $ref: '#/components/schemas/FeedURL'
        UpdatedAt:
          $ref: '#/components/schemas/UpdatedAt'
    APIItem:
      description: represents an individual item (e.g., an individual feed item).
      type: object
      required:
        - timestamp
        - ID
        - FeedID
        - URL
        - title
        - description
      allOf:
        - $ref: '#/components/schemas/MetadataFeed'
        - type: object
          required:
            - ID
            - FeedID
            - URL
          properties:
            ID:
              $ref: '#/components/schemas/ItemID'
            FeedID:
              $ref: '#/components/schemas/FeedID'
            URL:
              $ref: '#/components/schemas/ItemURL'
            UserProperties:
              $ref: '#/components/schemas/UserItemProperties'
    Tokens:
      type: object
      required:
        - IDToken
        - Claims
        - AccessToken
      properties:
        IDToken:
          x-go-type: '*oidc.IDToken'
          x-go-type-import:
            path: github.com/coreos/go-oidc
        Claims:
          type: object
          $ref: '#/components/schemas/Claims'
        AccessToken:
          type: string
    Claims:
      type: object
      properties:
        Subject:
          type: string
          x-oapi-codegen-extra-tags:
            json: 'sub'
          x-go-type-skip-optional-pointer: true
        SessionID:
          type: string
          x-oapi-codegen-extra-tags:
            json: 'sid'
          x-go-type-skip-optional-pointer: true
        UserName:
          type: string
          x-oapi-codegen-extra-tags:
            json: 'name'
          x-go-type-skip-optional-pointer: true
        UserPictureURL:
          type: string
          x-oapi-codegen-extra-tags:
            json: 'picture'
          x-go-type-skip-optional-pointer: true
        Issuer:
          type: string
          x-oapi-codegen-extra-tags:
            json: 'iss'
          x-go-type-skip-optional-pointer: true
        UserNickName:
          type: string
          x-oapi-codegen-extra-tags:
            json: 'nickname'
          x-go-type-skip-optional-pointer: true
        UpdatedAt:
          # x-go-type: 'time.Time'
          # type: string
          x-oapi-codegen-extra-tags:
            json: 'updated_at'
          x-go-type-skip-optional-pointer: true
        Audience:
          type: string
          x-oapi-codegen-extra-tags:
            json: 'aud'
          x-go-type-skip-optional-pointer: true
        Expiry:
          # x-go-type: 'time.Time'
          type: integer
          x-oapi-codegen-extra-tags:
            json: 'exp'
          x-go-type-skip-optional-pointer: true
        IssuedAt:
          # x-go-type: 'time.Time'
          type: integer
          x-oapi-codegen-extra-tags:
            json: 'iat'
          x-go-type-skip-optional-pointer: true
    ScheduledJob:
      description: represents a job that has been scheduled by the job scheduler.
      type: object
      required:
        - SchedulerID
        - Schedule
        - NextRun
        - Data
        - CreatedAt
      properties:
        CreatedAt:
          $ref: '#/components/schemas/CreatedAt'
        Schedule:
          type: string
          x-oapi-codegen-extra-tags:
            json: 'job_trigger'
            validate: 'required,cron'
          x-go-type-skip-optional-pointer: true
        NextRun:
          x-go-type: 'time.Time'
          x-oapi-codegen-extra-tags:
            json: 'job_next_run'
          x-go-type-skip-optional-pointer: true
        Options:
          x-go-type: '*quartz.JobDetailOptions'
          x-go-type-import:
            path: 'github.com/reugn/go-quartz/quartz'
          x-oapi-codegen-extra-tags:
            json: 'job_options,omitempty'
          x-go-type-skip-optional-pointer: true
        Data:
          type: object
          oneOf:
            - $ref: '#/components/schemas/FeedJob'
          x-oapi-codegen-extra-tags:
            json: 'job_data'
          x-go-type-skip-optional-pointer: true
        SchedulerID:
          $ref: '#/components/schemas/SchedulerID'
    FeedJob:
      description: represents a job that fetches new items for a feed.
      type: object
      required:
        - ID
        - URL
      properties:
        ID:
          $ref: '#/components/schemas/FeedID'
        URL:
          $ref: '#/components/schemas/URL'
    UserSession:
      description: tracks a user session.
      type: object
      required:
        - Token
        - Data
        - Expiry
      properties:
        Token:
          description: the session token for the user.
          type: string
          x-oapi-codegen-extra-tags:
            json: 'token'
        Data:
          description: the session data.
          x-go-type: '[]byte'
          x-oapi-codegen-extra-tags:
            json: 'data'
        Expiry:
          description: the time at which this session token expires.
          x-go-type: time.Time
          x-oapi-codegen-extra-tags:
            json: 'expiry'


