# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/schemas/v3.0/schema.yaml

# Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.
# SPDX-License-Identifier: 	AGPL-3.0-or-later

openapi: "3.0.3"
info:
  version: 1.0.0
  title: Server Spec
  description: OpenAPI spec for the Go Feed Me server.
paths:
  /:
    get:
      description: display the home page.
      operationId: index
      responses:
        200:
          $ref: "#/components/responses/htmx"
  /login/{provider}:
    get:
      summary: Process a user login with given provider
      operationId: login
      tags:
        - login
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
      responses:
        307:
          description: Redirect to provider
        404:
          description: No provider to satisfy login
        500:
          description: Problem with request
  /login/{provider}/callback:
    get:
      summary: Callback for login provider
      operationId: loginCallback
      tags:
        - login
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
      responses:
        307:
          description: Redirect to home
        401:
          description: Unauthorized
        404:
          description: No provider to satisfy login
        500:
          description: Problem with request
  /logout/{provider}:
    get:
      summary: Logout handler for provider
      operationId: logout
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
      responses:
        307:
          description: Redirect to provider
        500:
          description: Problem with request
  /user/new:
    get:
      description: >
        Add a new user.
      operationId: newUser
      responses:
        200:
          $ref: "#/components/responses/htmx"
    put:
      summary: >
        Save a new user.
      operationId: addUser
      requestBody:
        $ref: "#/components/requestBodies/UserSignupRequestBody"
      responses:
        200:
          $ref: "#/components/responses/htmx"
  /search:
    post:
      summary: Issue a user search request
      operationId: Search
      responses:
        200:
          $ref: "#/components/responses/htmx"
        401:
          description: Unauthorized
        500:
          description: Problem with request
      # requestBody:
      #   description: filters for results
      #   content:
      #     application/x-www-form-urlencoded:
      #       schema:
      #         $ref: 'models.yaml#/components/schemas/Filters'
  /home/settings:
    get:
      summary: Show user settings modal
      operationId: getHomeSettings
      responses:
        200:
          $ref: "#/components/responses/htmx"
        401:
          description: Unauthorized
        500:
          description: Problem with request
  /subscription/new:
    get:
      description: >
        Add a new subscription.
      operationId: newSubscription
      responses:
        200:
          $ref: "#/components/responses/htmx"
    put:
      summary: >
        Save a subscription.
      operationId: addSubscription
      requestBody:
        $ref: "#/components/requestBodies/SubscriptionRequestBody"
      responses:
        200:
          $ref: "#/components/responses/htmx"
  /subscription/{feed}:
    get:
      summary: >
        Show a subscription.
      operationId: showSubscription
      parameters:
        - $ref: "#/components/parameters/FeedID"
      responses:
        200:
          $ref: "#/components/responses/htmx"
    put:
      summary: >
        Save a subscription.
      operationId: saveSubscription
      parameters:
        - $ref: "#/components/parameters/FeedID"
      requestBody:
        $ref: "#/components/requestBodies/SubscriptionRequestBody"
      responses:
        200:
          $ref: "#/components/responses/htmx"
    delete:
      summary: >
        Remove a subscription.
      operationId: removeSubscription
      parameters:
        - $ref: "#/components/parameters/FeedID"
      responses:
        200:
          $ref: "#/components/responses/htmx"
  /subscription/category:
    put:
      summary: >
        Add a category to a subscription
      operationId: addSubscriptionCategory
      requestBody:
        $ref: "#/components/requestBodies/CategoryRequestBody"
      responses:
        200:
          $ref: "#/components/responses/htmx"
    delete:
      summary: >
        Remove a category from a subscription.
      operationId: removeSubscriptionCategory
      responses:
        200:
          $ref: "#/components/responses/htmx"
  /home:
    get:
      summary: >
        Shows a page of curated feeds and content based on the user's
        subscriptions and viewing preferences.
      operationId: handleHome
      responses:
        200:
          $ref: "#/components/responses/htmx"
  /home/feeds:
    get:
      summary: >
        Shows feeds with optional filtering applied.
      operationId: handleShowFeeds
      parameters:
        - $ref: "#/components/parameters/FeedIDs"
        - $ref: "#/components/parameters/Categories"
        - $ref: "#/components/parameters/View"
        - $ref: "#/components/parameters/Count"
        - $ref: "#/components/parameters/Pagination"
      responses:
        200:
          $ref: "#/components/responses/htmx"
    post:
      summary: >
        Mark feeds.
      operationId: handleMarkFeeds
      requestBody:
        $ref: "#/components/requestBodies/MarkRequest"
      responses:
        200:
          $ref: "#/components/responses/htmx"
  /home/items:
    get:
      summary: >
        Shows items with optional filtering applied.
      operationId: handleShowItems
      parameters:
        - $ref: "#/components/parameters/FeedIDs"
        - $ref: "#/components/parameters/Categories"
        - $ref: "#/components/parameters/View"
        - $ref: "#/components/parameters/Count"
        - $ref: "#/components/parameters/Pagination"
      responses:
        200:
          $ref: "#/components/responses/htmx"
    post:
      summary: >
        Mark feeds.
      operationId: handleMarkItems
      requestBody:
        $ref: "#/components/requestBodies/MarkRequest"
      responses:
        200:
          $ref: "#/components/responses/htmx"
  /home/{feed}/{item}:
    summary: >
      Handle item.
    parameters:
      - $ref: "#/components/parameters/FeedID"
      - $ref: "#/components/parameters/ItemID"
    get:
      summary: >
        Shows a feed item.
      operationId: handleShowItem
      responses:
        200:
          $ref: "#/components/responses/htmx"
    put:
      summary: >
        Save a feed item to the user's saved items.
      operationId: handleSaveItem
      responses:
        200:
          $ref: "#/components/responses/htmx"
    delete:
      summary: >
        Remove a feed item from the user's saved items.
      operationId: handleUnsaveItem
      responses:
        200:
          $ref: "#/components/responses/htmx"
  /home/{feed}/{item}/{mark}:
    summary: >
      Handle marking item.
    post:
      summary: >
        Mark a feed item.
      operationId: handleMarkItem
      parameters:
        - $ref: "#/components/parameters/FeedID"
        - $ref: "#/components/parameters/ItemID"
        - $ref: "#/components/parameters/Mark"
      responses:
        200:
          $ref: "#/components/responses/htmx"
components:
  schemas:
    MarkCommon:
      description: contains common data for marking objects.
      type: object
      required:
        - mark
      properties:
        mark:
          $ref: "api.yaml#/components/schemas/Mark"
    MarkFeeds:
      description: contains data for marking Feeds.
      type: object
      allOf:
        - $ref: "#/components/schemas/MarkCommon"
        - type: object
          required:
            - feeds
          properties:
            feeds:
              $ref: "models.yaml#/components/schemas/FeedIDs"
    MarkItems:
      description: contains data for marking Items.
      type: object
      allOf:
        - $ref: "#/components/schemas/MarkCommon"
        - type: object
          required:
            - items
          properties:
            items:
              $ref: "models.yaml#/components/schemas/ItemIDs"
    MarkCategories:
      description: contains data for marking Categories.
      type: object
      allOf:
        - $ref: "#/components/schemas/MarkCommon"
        - type: object
          required:
            - categories
          properties:
            categories:
              $ref: "models.yaml#/components/schemas/Categories"
    MarkObjects:
      description: mark one or more objects
      type: object
      oneOf:
        - $ref: "#/components/schemas/MarkFeeds"
        - $ref: "#/components/schemas/MarkItems"
        - $ref: "#/components/schemas/MarkCategories"
  parameters:
    # Path parameters:
    FeedID:
      name: feed
      in: path
      required: true
      schema:
        $ref: "models.yaml#/components/schemas/FeedID"
    ItemID:
      name: item
      in: path
      required: true
      schema:
        $ref: "models.yaml#/components/schemas/ItemID"
    Mark:
      name: mark
      in: path
      required: true
      schema:
        $ref: "api.yaml#/components/schemas/Mark"
    # Query Parameters:
    View:
      name: view
      in: query
      required: true
      schema:
        $ref: "api.yaml#/components/schemas/View"
      x-oapi-codegen-extra-tags:
        validate: "required,oneof='read unread all'"
    Count:
      name: count
      in: query
      required: true
      schema:
        $ref: "api.yaml#/components/schemas/Count"
      x-oapi-codegen-extra-tags:
        validate: "required,numeric,gt=0,lt=20"
    FeedIDs:
      name: feeds
      in: query
      schema:
        $ref: "models.yaml#/components/schemas/FeedIDs"
      x-oapi-codegen-extra-tags:
        form: "feeds[]"
        validate: "unique,dive,startswith=feed_"
    ItemIDs:
      name: items
      in: query
      schema:
        $ref: "models.yaml#/components/schemas/ItemIDs"
      x-oapi-codegen-extra-tags:
        form: "items[]"
        validate: "unique,dive,startswith=item_"
    Categories:
      name: categories
      in: query
      schema:
        $ref: "models.yaml#/components/schemas/Categories"
      x-oapi-codegen-extra-tags:
        form: "categories[]"
        validate: "unique"
    Pagination:
      name: pagination
      in: query
      schema:
        $ref: "api.yaml#/components/schemas/Pagination"
      x-oapi-codegen-extra-tags:
        validate: "url_encoded"
  requestBodies:
    MarkRequest:
      description: >
        Holds options for marking objects.
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: "#/components/schemas/MarkObjects"
    UserSignupRequestBody:
      description: >
        Holds details for adding/saving a user signup.
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: "api.yaml#/components/schemas/APIUserSignupRequest"
    SubscriptionRequestBody:
      description: >
        Holds details for adding/saving a subscription.
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: "api.yaml#/components/schemas/APISubscriptionRequest"
    CategoryRequestBody:
      description: >
        A list of categories to add/remove from a subscription.
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            type: object
            required:
              - Category
            properties:
              Category:
                $ref: "models.yaml#/components/schemas/Category"
  responses:
    htmx:
      description: standard htmx powered response.
      content:
        "text/html;charset=utf-8": {}
