openapi: '3.1.0'
info:
  version: 1.0.0
  title: Admin API
  description: The admin-only portion of the API, which has its own separate OpenAPI spec
paths:
  /:
    get:
      description: display the home page.
      operationId: index
      responses:
        200:
          $ref: '#/components/responses/htmx'
  /login/{provider}:
    get:
      summary: Process a user login with given provider
      operationId: login
      tags:
        - login
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
      responses:
        307:
          description: Redirect to provider
        404:
          description: No provider to satisfy login
        500:
          description: Problem with request
  /login/{provider}/callback:
    get:
      summary: Callback for login provider
      operationId: loginCallback
      tags:
        - login
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
      responses:
        307:
          description: Redirect to home
        401:
          description: Unauthorized
        404:
          description: No provider to satisfy login
        500:
          description: Problem with request
  /logout/{provider}:
    get:
      summary: Logout handler for provider
      operationId: logout
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
      responses:
        307:
          description: Redirect to provider
        500:
          description: Problem with request
  /signup:
    summary: Display a sign-up form.
    get:
      summary: User sign up
      operationId: signup
      responses:
        200:
          $ref: '#/components/responses/htmx'
        400:
          description: Bad request (not htmx)
        500:
          description: Error rendering signup form
    post:
      summary: Process sign up request
      operationId: processSignup
      requestBody:
        description: New user information
        content:
          multipart/form-data:
            schema:
              $ref: '../models/api.yaml#/components/schemas/UserSignup'
      responses:
        200:
          $ref: '#/components/responses/htmx'
        500:
          description: Error processing signup
  /search:
    post:
      summary: Issue a user search request
      operationId: Search
      responses:
        200:
          $ref: '#/components/responses/htmx'
        401:
          description: Unauthorized
        500:
          description: Problem with request
      # requestBody:
      #   description: filters for results
      #   content:
      #     application/x-www-form-urlencoded:
      #       schema:
      #         $ref: '../models/api.yaml#/components/schemas/Filters'
  /home/settings:
    get:
      summary: Show user settings modal
      operationId: getHomeSettings
      responses:
        200:
          $ref: '#/components/responses/htmx'
        401:
          description: Unauthorized
        500:
          description: Problem with request
  /home/subscription/add:
    get:
      summary: Add a new subscription
      operationId: addSubscription
      responses:
        200:
          $ref: '#/components/responses/htmx'
        401:
          description: Unauthorized
        500:
          description: Problem with request
    post:
      summary: Process a new subscription
      operationId: processAddSubscription
      requestBody:
        description: New user information
        content:
          multipart/form-data:
            schema:
              $ref: '../models/api.yaml#/components/schemas/SubscriptionRequest'
      responses:
        200:
          $ref: '#/components/responses/htmx'
        401:
          description: Unauthorized
        500:
          description: Problem with subscription
  /home/subscription/edit/{feed}:
    get:
      summary: Edit a new subscription
      operationId: getSubscriptionEdit
      parameters:
        - $ref: '#/components/parameters/FeedID'
          required: true
      responses:
        200:
          $ref: '#/components/responses/htmx'
        401:
          description: Unauthorized
        500:
          description: Problem with request
    post:
      summary: Process a subscription edit
      operationId: postSubscriptionEdit
      parameters:
        - $ref: '#/components/parameters/FeedID'
          required: true
      requestBody:
        description: New user information
        content:
          multipart/form-data:
            schema:
              $ref: '../models/api.yaml#/components/schemas/SubscriptionRequest'
      responses:
        200:
          $ref: '#/components/responses/htmx'
        401:
          description: Unauthorized
        500:
          description: Problem with request
  /home/show/{list}:
    get:
      summary: >
        display a list of type {list}, with optional filtering.
      operationId: showList
      parameters:
        # Path:
        - $ref: '#/components/parameters/List'
        # Query:
        - $ref: '#/components/parameters/FeedIDs'
        - $ref: '#/components/parameters/ItemIDs'
        - $ref: '#/components/parameters/Categories'
        - $ref: '#/components/parameters/Count'
        - $ref: '#/components/parameters/Pagination'
        - $ref: '#/components/parameters/ViewState'
      responses:
        200:
          $ref: '#/components/responses/htmx'
  /home/set/{list}/{state}:
    post:
      summary: >
        set a list of type {list} with {state}, with optional filtering.
      operationId: setListState
      parameters:
        # Path:
        - $ref: '#/components/parameters/List'
        - $ref: '#/components/parameters/State'
        # Query:
        - $ref: '#/components/parameters/FeedIDs'
        - $ref: '#/components/parameters/ItemIDs'
        - $ref: '#/components/parameters/Categories'
      responses:
        200:
          $ref: '#/components/responses/htmx'
  /home/show/article/{feed}/{item}:
    get:
      summary: display an item as an article.
      operationId: showArticle
      parameters:
        - $ref: '#/components/parameters/FeedID'
          required: true
        - $ref: '#/components/parameters/ItemID'
          required: true
      responses:
        200:
          $ref: '#/components/responses/htmx'
  /home/set/article/{feed}/{item}/{state}:
    post:
      summary: mark an article with {mark}.
      operationId: setArticleState
      parameters:
        - $ref: '#/components/parameters/FeedID'
        - $ref: '#/components/parameters/ItemID'
        - $ref: '#/components/parameters/State'
    responses:
        200:
          $ref: '#/components/responses/htmx'
  /home/{action}/article/{feed}/{item}:
    post:
      summary: perform {action} on an article.
      operationId: actionArticle
      parameters:
        - $ref: '#/components/parameters/Action'
        - $ref: '#/components/parameters/FeedID'
        - $ref: '#/components/parameters/ItemID'
    responses:
        200:
          $ref: '#/components/responses/htmx'
components:
  parameters:
  # Query parameters:
    FeedIDs:
      name: feeds
      in: query
      schema:
        $ref: '../models/api.yaml#/components/schemas/FeedIDs'
    ItemIDs:
      name: items
      in: query
      schema:
        $ref: '../models/api.yaml#/components/schemas/ItemIDs'
    # IDs:
    #   name: ids
    #   in: query
    #   schema:
    #     $ref: '../models/api.yaml#/components/schemas/IDs'
    #   x-go-type-skip-optional-pointer: true
    Categories:
      name: categories
      in: query
      schema:
        $ref: '../models/api.yaml#/components/schemas/Categories'
    ShowUnread:
      name: show_unread
      in: query
      schema:
        $ref: '../models/api.yaml#/components/schemas/ShowUnread'
    Pagination:
      name: pagination
      in: query
      schema:
        $ref: '../models/api.yaml#/components/schemas/Pagination'
    Count:
      name: count
      in: query
      schema:
        $ref: '../models/api.yaml#/components/schemas/Count'
    ViewState:
      name: state
      description: >
        the state of objects.
      in: query
      schema:
        $ref: '../models/api.yaml#/components/schemas/State'
  # Path parameters:
    List:
      name: list
      description: >
        the type of a list of objects.
      in: path
      schema:
        $ref: '../models/api.yaml#/components/schemas/APIListType'
    State:
      name: state
      description: >
        the type of state to set on objects.
      in: path
      schema:
        $ref: '../models/api.yaml#/components/schemas/State'
    Action:
      name: action
      description: >
        an action to perform on objects.
      in: path
      schema:
        $ref: '../models/api.yaml#/components/schemas/APIAction'
    FeedID:
      name: feed
      in: path
      schema:
        $ref: '../models/api.yaml#/components/schemas/FeedID'
    ItemID:
      name: item
      in: path
      schema:
        $ref: '../models/api.yaml#/components/schemas/ItemID'
  responses:
    htmx:
      description: standard htmx powered response.
      content:
        'text/html;charset=utf-8': {}
