#:schema https://json.schemastore.org/any.json

[[releases]]
version   = "v0.176"
date      = "June 29, 2026"
type      = "minor"
is_latest = true
[[releases.changes]]
type = "new"
description = """
Searching for new feeds will now show results that match the site's domain (i.e., github, reddit, etc.)
"""

[[releases]]
version = "v0.173"
date    = "June 29, 2026"
type    = "minor"
[[releases.changes]]
type = "improved"
description = """
Fetching remote content should result in better detection and extraction of the main article content and media.
"""

[[releases]]
version = "v0.170"
date    = "June 25, 2026"
type    = "major"
[[releases.changes]]
type = "new"
description = """
Add a button to edit the subscription when viewing all articles from a subscription.
"""
[[releases.changes]]
type = "new"
description = """
Added a blog post about article filtering.
"""
[[releases.changes]]
type = "improved"
description = """
More subtle buttons and icons on subscriptions/articles list pages.
"""
[[releases.changes]]
type = "improved"
description = """
Better layout of stats when stats are shown on subscription cards.
"""
[[releases.changes]]
type = "fixed"
description = """
When clicking on a category badge on an article to filter by that category, the articles will be filtered to the category and that subscription, not all subscriptions.
"""

[[releases]]
version = "v0.167"
date    = "June 19, 2026"
type    = "patch"
[[releases.changes]]
type = "improved"
description = """
Internal performance fixes.
"""
[[releases.changes]]
type = "fixed"
description = """
Billing logic fixes.
"""

[[releases]]
version = "v0.166"
date    = "June 19, 2026"
type    = "patch"
[[releases.changes]]
type = "fixed"
description = """
Fixed the button on the add subscription page to generate your email address for subscribing to email newsletters.
"""

[[releases]]
version = "v0.164"
date    = "June 18, 2026"
type    = "patch"
[[releases.changes]]
type = "fixed"
description = """
Fixed logic around user trials. Apologies if you signed up and saw a message your trial already expired. That was wrong!
"""
[[releases.changes]]
type = "improved"
description = """
On pages with back buttons, hitting the back button will load fresh content on the page you return to. This means editing a subscription and going back to the subscription will show your edits immediately.
"""

[[releases]]
version = "v0.163"
date    = "June 17, 2026"
type    = "major"
[[releases.changes]]
type = "new"
description = """
Home, Subscriptions and Articles pages now use a masonry style grid layout on desktop screens, for better packing of cards.
"""
[[releases.changes]]
type = "new"
description = """
When toggling read status of a subscription/article, the card will now change brightness rather than disappear.
"""

[[releases]]
version = "v0.160"
date    = "June 15, 2026"
type    = "major"
[[releases.changes]]
type = "new"
description = """
Tabbed Favorites page for easier navigation with larger number of favorites.
"""
[[releases.changes]]
type = "new"
description = """
Easily add new subscriptions from sidebar/dock.
"""
[[releases.changes]]
type = "improved"
description = """
Behind the scenes performance fixes should increase stability and speed.
"""
[[releases.changes]]
type = "improved"
description = """
Styling improvements. Consistent page/section headings. Tooltips on card actions/menu in footer.
"""

[[releases]]
version = "v0.159"
date    = "June 8, 2026"
type    = "minor"
[[releases.changes]]
type = "new"
description = """
Foragd will now automically detect feeds for medium.com blogs/pages.
"""

[[releases]]
version = "v0.158"
date    = "June 8, 2026"
type    = "minor"
[[releases.changes]]
type = "improved"
description = """
Improved article card styling.
"""
[[releases.changes]]
type = "new"
description = """
Backend changes for Android app support (app coming soon!)
"""

[[releases]]
version = "v0.156"
date    = "June 8, 2026"
type    = "minor"
[[releases.changes]]
type = "improved"
description = """
New user home page has been revamped. Easier to navigate and cleaner styling.
"""
[[releases.changes]]
type = "new"
description = """
Changelog is now linked in header and user actions menu.
"""
[[releases.changes]]
type = "improved"
description = """
On the add subscription page, the additional instructions are now source-specific.
"""

[[releases]]
version = "v0.155"
date    = "June 5, 2026"
type    = "minor"
[[releases.changes]]
type = "improved"
description = """
More vibrant notifications. Notifications now have a color that reflects their severity, making the status more obvious.
"""

[[releases]]
version = "v0.154"
date    = "June 4, 2026"
type    = "major"
[[releases.changes]]
type = "new"
description = """
You can now add Google News RSS feeds easily. On the <a class="link" href="/subscription/add">Add Subscription</a> page, switch the source to 'Google News' and enter a search query to generate a feed for that query.
"""

[[releases]]
version = "v0.153"
date    = "June 3, 2026"
type    = "major"
[[releases.changes]]
type        = "new"
description = "Added a changelog page."

[[releases]]
version = "v0.152"
date    = "June 3, 2026"
type    = "patch"
[[releases.changes]]
type        = "improved"
description = "Foragd now suggests a colour for the browser or OS to use when rendering surfaces around the site based on your theme."
[[releases.changes]]
type        = "improved"
description = "OPML export has been streamlined."
[[releases.changes]]
type        = "improved"
description = "The informed/inspired/enlightened starter feedsets have been updated and now generated dynamically."


[[releases]]
version = "v0.151"
date    = "Jun 2, 2026"
type    = "patch"
[[release.changes]]
type        = "fixed"
description = "You can now focus the global search box with Alt+k again."
[[releases.changes]]
type        = "improved"
description = "Foragd will try to protect you from breaching your account limits."

[[releases]]
version = "v0.150"
date    = "May 29, 2026"
type    = "major"
[[releases.changes]]
type = "new"
description = """
There is now a <a class="link" href="/user/settings#subscriptions">dedicated page</a> for bulk and individual management of all your subscriptions.
"""
