run:
  timeout: 5m
  relative-path-mode: gomod

output:
  sort-results: true
  sort-order:
    - linter
    - severity
    - file
  show-stats: true

linters:
  disable-all: true
  enable:
    # - asasalint
    # - asciicheck
    # - bidichk
    - bodyclose
    - canonicalheader
    # - containedctx
    # - contextcheck
    - copyloopvar
    # - cyclop
    # - decorder
    # - depguard
    # - dogsled
    - dupl
    - dupword
    - durationcheck
    # - err113
    - errcheck
    # - errchkjson
    - errname
    - errorlint
    # - exhaustive
    # - exhaustruct
    # - exportloopref # govet already reports an error when loop variable is captured by func literal so this linter is not needed.
    - fatcontext
    - forbidigo
    # - forcetypeassert # This check can be enabled through errcheck with check-type-assertions.
    - funlen
    # - gci
    # - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    # - gochecksumtype
    - gocognit
    - goconst
    # - gocritic
    # - gocyclo
    - godot
    # - godox
    # - gofmt # gofumpt includes formatting rules that are a superset of gofmt.
    # - gofumpt
    - goheader
    - goimports # gci has equivalent/better functionality.
    # - gomoddirectives
    # - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    # - grouper
    # - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    # - loggercheck
    # - maintidx
    # - makezero
    - mirror
    - misspell
    # - mnd
    - musttag
    - nakedret
    # - nestif
    - nilerr
    - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    # - nonamedreturns
    - nosprintfhostport
    # - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    # - promlinter
    # - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    # - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    # - tagalign
    - tagliatelle
    # - tenv
    - testableexamples
    - testifylint
    # - testpackage
    # - thelper
    # - tparallel
    - typecheck
    - unconvert
    # - unparam
    - unused
    - usestdlibvars
    - varnamelen
    # - wastedassign
    # - whitespace
    - wrapcheck
    # - wsl
    # - zerologlint

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - bodyclose
        - dupl
        - errcheck
        - funlen
        - goconst
        - gosec
        - noctx
        - wrapcheck
  exclude-files:
    - '(.+)\.gen\.go$'
    - "(.+)_generated.go$"
  max-same-issues: 50

severity:
  default-severity: "@linter"
  case-sensitive: false

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 30
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 10.0
  errcheck:
    check-blank: true
    check-type-assertions: true
  exhaustive:
    # Program elements to check for exhaustiveness.
    # Default: [ switch ]
    check:
      - switch
      - map
  exhaustruct:
    # List of regular expressions to exclude struct packages and their names from checks.
    # Regular expressions must match complete canonical struct package/name/structname.
    # Default: []
    exclude:
      # std libs
      - "^net/http.Client$"
      - "^net/http.Cookie$"
      - "^net/http.Request$"
      - "^net/http.Response$"
      - "^net/http.Server$"
      - "^net/http.Transport$"
      - "^net/url.URL$"
      - "^os/exec.Cmd$"
      - "^reflect.StructField$"
  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
    lines: 100
    # Checks the number of statements in a function.
    # If lower than 0, disable the check.
    # Default: 40
    statements: 50
    # Ignore comments when counting lines.
    # Default false
    ignore-comments: true
  gochecksumtype:
    # Presence of `default` case in switch statements satisfies exhaustiveness, if all members are not listed.
    # Default: true
    default-signifies-exhaustive: false
  gocognit:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 20
  gocritic:
    # Settings passed to gocritic.
    # The settings key is the name of a supported gocritic checker.
    # The list of supported checkers can be find in https://go-critic.github.io/overview.
    settings:
      captLocal:
        # Whether to restrict checker to params only.
        # Default: true
        paramsOnly: false
      underef:
        # Whether to skip (*x).method() calls where x is a pointer receiver.
        # Default: true
        skipRecvDeref: false
  govet:
    enable-all: true
    disable:
      - asmdecl # (not needed) reports mismatches between assembly files and Go declarations.
      - assign # (dupl staticcheck) detects useless assignments.
      - cgocall # (not needed) detects some violations of the cgo pointer passing rules.
      - fieldalignment # (not needed) detects structs that would use less memory if their fields were sorted.
      - findcall # (not needed) serves as a trivial example and test of the Analysis API.
      - framepointer # (not needed) reports assembly code that clobbers the frame pointer before saving it.
      - structtag # (dupl revive struct-tag) defines an Analyzer that checks struct field tags are well formed.
      - copylocks
    settings:
      shadow:
        # Whether to be strict about shadowing; can be noisy.
        # Default: false
        strict: true
  inamedparam:
    # Skips check for interface methods with only a single parameter.
    # Default: false
    skip-single-param: true
  mnd:
    # List of function patterns to exclude from analysis.
    # Values always ignored: `time.Date`,
    # `strconv.FormatInt`, `strconv.FormatUint`, `strconv.FormatFloat`,
    # `strconv.ParseInt`, `strconv.ParseUint`, `strconv.ParseFloat`.
    # Default: []
    ignored-functions:
      - args.Error
      - flag.Arg
      - flag.Duration.*
      - flag.Float.*
      - flag.Int.*
      - flag.Uint.*
      - os.Chmod
      - os.Mkdir.*
      - os.OpenFile
      - os.WriteFile
  nolintlint:
    # Exclude following linters from requiring an explanation.
    # Default: []
    allow-no-explanation: [funlen, gocognit, lll]
    # Enable to require an explanation of nonzero length after each nolint directive.
    # Default: false
    require-explanation: true
    # Enable to require nolint directives to mention the specific linter being suppressed.
    # Default: false
    require-specific: true
  perfsprint:
    errorf: false
    strconcat: false
  reassign:
    # Patterns for global variable names that are checked for reassignment.
    # See https://github.com/curioswitch/go-reassign#usage
    # Default: ["EOF", "Err.*"]
    patterns:
      - ".*"
  misspell:
    locale: US # US is common spelling.
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
  varnamelen:
    ignore-names:
      - err
      - wg
      - tt
      - id
      - ok
      - mu
      - db
      - tx
  revive:
    enable-all-rules: true
    confidence: 0.8
    ignore-generated-header: false
    rules:
      - name: context-keys-type # Covered by staticcheck SA1029.
        disabled: true
      - name: time-naming # Covered by stylecheck ST1011.
        disabled: true
      - name: errorf # Covered by gosimple S1028.
        disabled: true
      - name: dot-imports # Covered by stylecheck ST1001.
        disabled: true
      - name: error-return # Covered by stylecheck ST1008.
        disabled: true
      - name: error-strings # Covered by stylecheck ST1005.
        disabled: true
      - name: error-naming # Covered by stylecheck ST1012.
        disabled: true
      - name: var-naming # Covered by stylecheck ST1003.
        disabled: true
      - name: package-comments
        disabled: true
      - name: range # Covered by gofumpt.
        disabled: true
      - name: receiver-naming # Covered by stylecheck ST1006.
        disabled: true
      - name: cyclomatic # Covered by gocognit.
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: file-header
        disabled: true
      - name: empty-block # Covered by staticcheck SA9003.
        disabled: true
      - name: confusing-results # Covered more comprehensively by gocritic unnamedResult.
        disabled: true
      - name: unreachable-code # Covered by govet unreachable check.
        disabled: true
      - name: add-constant # Covered by goconst.
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: unnecessary-stmt # Covered by gosimple S1023.
        disabled: true
      - name: bool-literal-in-expr # Covered by gosimple S1002.
        disabled: true
      - name: imports-blocklist
        disabled: true
      - name: range-val-in-closure # Covered by govet loopclosure check.
        disabled: true
      - name: waitgroup-by-value # Covered by govet copylocks check.
        disabled: true
      - name: atomic # Covered by govet atomic check.
        disabled: true
      - name: empty-lines # Covered by gofumpt.
        disabled: true
      - name: line-length-limit # Covered by lll.
        disabled: true
      - name: duplicated-imports # Covered by stylecheck ST1019.
        disabled: true
      - name: unhandled-error # Covered by errcheck.
        disabled: true
      - name: cognitive-complexity # Covered by gocognit.
        disabled: true
      - name: string-of-int # Covered by govet stringintconv check.
        disabled: true
      - name: function-length
        disabled: true
      - name: unused-receiver
        disabled: true
      - name: useless-break # Covered by staticcheck SA4011.
        disabled: true
      - name: banned-characters
        disabled: true
      - name: enforce-repeated-arg-type-style # Covered by govet.
        disabled: true
      - name: max-control-nesting # Covered by cocognit.
        disabled: true
      - name: argument-limit
        arguments:
          - 5
      - name: function-result-limit
        arguments:
          - 3
  goimports:
    local-prefixes: github.com/joshuar/go-hass-agent
  dupl:
    threshold: 100
  gci:
    sections:
      - blank # Blank section: contains all blank imports.
      - dot # Dot section: contains all dot imports.
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - alias # Alias section: contains all alias imports.
      - prefix(github.com/joshuar) # Custom section: groups all imports with the specified Prefix.
    skip-generated: true
    custom-order: true
  goconst:
    min-len: 2
    min-occurrences: 3
    ignore-tests: true
  lll:
    line-length: 140
  gosec:
    excludes:
      - G204
  sloglint:
    # Enforce not mixing key-value pairs and attributes.
    # Default: true
    no-mixed-args: false
    # Enforce using key-value pairs only (overrides no-mixed-args, incompatible with attr-only).
    # Default: false
    kv-only: false
    # Enforce using attributes only (overrides no-mixed-args, incompatible with kv-only).
    # Default: false
    attr-only: true
    # Enforce using static values for log messages.
    # Default: false
    static-msg: true
    # Enforce using constants instead of raw keys.
    # Default: false
    no-raw-keys: false
    # Enforce a single key naming convention.
    # Values: snake, kebab, camel, pascal
    # Default: ""
    key-naming-case: snake
    # Enforce putting arguments on separate lines.
    # Default: false
    args-on-sep-lines: true
