openapi: 3.0.3
info:
  version: 1.0.0
  title: Request Objects
  description: >
    Request objects used within the service.
  license:
    name: AGPL 3.0
    idenfiier: AGPL-3.0-or-later
  contact:
    name: Immanent Tech
components:
  schemas:
    APIError:
      description: >
        represents an error returned from any API within the service/application.
      type: object
      required:
        - status_code
      properties:
        internal_error:
          description: >
            is the low-level, internal error.
          x-go-type: error
          x-go-type-skip-optional-pointer: true
          x-omit-zero: true
        status_code:
          description: >
            is the status code associated with the error. Usually, this is a HTTP status code.
          type: integer
        user_message:
          $ref: 'models.yaml#/components/schemas/UserMessage'
      additionalProperties: true
    AddCategoryToSubscriptionRequest:
      description: >
        is a request to add a new category to a subscription.
      type: object
      required:
        - category
      properties:
        category:
          $ref: 'models.yaml#/components/schemas/Category'
        existing_categories:
          description: >
            is a list of categories already assigned to the subscription.
          type: array
          items:
            $ref: 'models.yaml#/components/schemas/Category'
          x-oapi-codegen-extra-tags:
            form: 'customisation.categories'
          x-go-type-skip-optional-pointer: true
    FeedSubscriptionRequest:
      description: >
        is a request to add a new feed subscription.
      type: object
      required:
        - URL
        - subscription_id
      properties:
        URL:
          description: is the URL of the feed data. Used when adding a new feed subscription.
          type: string
          x-go-name: URL
          x-oapi-codegen-extra-tags:
            form: 'url'
            validate: 'required_without=SubscriptionID,omitempty,url'
        subscription_id:
          description: is the existing subscription ID. Will be empty when adding a new feed subscription.
          type: string
          x-go-name: SubscriptionID
          x-oapi-codegen-extra-tags:
            form: 'subscription_id'
            validate: 'required_without=URL,omitempty,startswith=sub_'
        customisation:
          $ref: 'models.yaml#/components/schemas/SubscriptionCustomisation'
        settings:
          allOf:
            - $ref: 'models.yaml#/components/schemas/SubscriptionSettings'
          x-oapi-codegen-extra-tags:
            form: 'settings'
        article_filters:
          $ref: 'models.yaml#/components/schemas/SubscriptionArticleFilters'
        suggestedCategories:
          description: >
            is a list of suggested categories for the subscription.
          type: array
          items:
            $ref: 'models.yaml#/components/schemas/Category'
          x-oapi-codegen-extra-tags:
            form: '-'
            json: '-'
          x-go-type-skip-optional-pointer: true
    FeedSubscriptionResult:
      description: >
        is the result of adding a feed subscription.
      type: object
      properties:
        request:
          $ref: '#/components/schemas/FeedSubscriptionRequest'
        error:
          $ref: 'models.yaml#/components/schemas/APIError'
        subscription:
          $ref: 'models.yaml#/components/schemas/Subscription'
    GroupSubscriptionRequest:
      description: >
        represents a request to create a group subscription.
      type: object
      required:
        - subscriptions
      properties:
        subscription_id:
          description: >
            will be a subscription ID if the user is editing an existing group subscription.
          allOf:
            - $ref: 'models.yaml#/components/schemas/SubscriptionID'
          x-go-name: SubscriptionID
          x-oapi-codegen-extra-tags:
            json: '-'
            form: 'subscription_id'
            validate: 'omitempty,startswith=sub_'
        subscriptions:
          description: >
            contains details of the subscriptions in the group.
          x-go-type: 'map[SubscriptionID]string'
          x-oapi-codegen-extra-tags:
            form: 'subscriptions'
            validate: 'required'
        customisation:
          allOf:
            - $ref: 'models.yaml#/components/schemas/SubscriptionCustomisation'
          x-oapi-codegen-extra-tags:
            form: 'customisation'
        settings:
          allOf:
            - $ref: 'models.yaml#/components/schemas/SubscriptionSettings'
          x-oapi-codegen-extra-tags:
            form: 'settings'
        article_filters:
          $ref: 'models.yaml#/components/schemas/SubscriptionArticleFilters'
        suggestedCategories:
          description: >
            is a list of suggested categories for the subscription.
          type: array
          items:
            $ref: 'models.yaml#/components/schemas/Category'
          x-oapi-codegen-extra-tags:
            form: '-'
            json: '-'
          x-go-type-skip-optional-pointer: true
        suggestedSubscriptions:
          description: >
            is a list of suggested subscriptions for the subscription.
          x-go-type: 'Subscriptions'
          x-oapi-codegen-extra-tags:
            form: '-'
            json: '-'
          x-go-type-skip-optional-pointer: true
    AddSubscriptionToGroupRequest:
      description: >
        is a request to add a new subscription to a group subscription.
      type: object
      required:
        - suggestion_text
        - suggestions
      properties:
        suggestion_text:
          description: >
            is the name of the new subscription to add.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'suggestion_text'
            validate: 'required'
        suggestions:
          description: >
            is the subscription suggestions.
          x-go-type: 'map[SubscriptionID]string'
          x-oapi-codegen-extra-tags:
            form: 'suggestions'
        existing_subscriptions:
          description: >
            is the existing subscriptions in the group.
          x-go-type: 'map[SubscriptionID]string'
          x-oapi-codegen-extra-tags:
            form: 'subscriptions'
          x-go-type-skip-optional-pointer: true
    AddSubscriptionToSearchRequest:
      description: >
        is a request to add a new subscription to a search subscription.
      type: object
      required:
        - selected_subscription
      properties:
        selected_subscription:
          description: >
            is the name of the subscription that was selected from the suggestions.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'subscription-suggestion-text'
        suggested_subscriptions:
          description: >
            is a list of the subscription suggestions.
          x-go-type: map[SubscriptionID]string
          x-oapi-codegen-extra-tags:
            form: subscription_suggestions
          x-go-type-skip-optional-pointer: true
    ListSubscriptionsResponse:
      description: >
        contains the data retrieved and relevant for listing subscriptions.
      type: object
      required:
        - subscriptions
        - filters
        - pagination
      properties:
        subscriptions:
          description: >
            is the list of subscriptions.
          x-go-type: Subscriptions
        latest_articles:
          description: >
            is a map of the latest articles for each subscription in the result.
          x-go-type: sync.Map
        filters:
          $ref: 'models.yaml#/components/schemas/ListFilters'
        pagination:
          $ref: 'models.yaml#/components/schemas/Pagination'
    ListArticlesResponse:
      description: >
        contains the data retrieved and relevant for listing articles.
      type: object
      required:
        - articles
        - category_counts
        - filters
        - pagination
      properties:
        subscription:
          allOf:
            - $ref: 'models.yaml#/components/schemas/Subscription'
          x-go-type-skip-optional-pointer: false
        articles:
          x-go-type: Articles
          # description: >
          #   is a list of subscriptions.
          # type: array
          # items:
          #   $ref: '#/components/schemas/Subscription'
          # x-go-type-skip-optional-pointer: true
        filters:
          $ref: 'models.yaml#/components/schemas/ListFilters'
        pagination:
          $ref: 'models.yaml#/components/schemas/Pagination'
