openapi: 3.0.3
info:
  version: 1.0.0
  title: Request Objects
  description: >
    Request objects used within the service.
  license:
    name: AGPL 3.0
    idenfiier: AGPL-3.0-or-later
  contact:
    name: Immanent Tech
components:
  schemas:
    APIError:
      description: >
        represents an error returned from any API within the service/application.
      type: object
      required:
        - status_code
      properties:
        internal_error:
          description: >
            is the low-level, internal error.
          x-go-type: error
          x-go-type-skip-optional-pointer: true
          x-omit-zero: true
        status_code:
          description: >
            is the status code associated with the error. Usually, this is a HTTP status code.
          type: integer
        user_message:
          $ref: 'models.yaml#/components/schemas/UserMessage'
      additionalProperties: true
    AddCategoryToSubscriptionRequest:
      description: >
        is a request to add a new category to a subscription.
      type: object
      required:
        - category
      properties:
        category:
          $ref: 'models.yaml#/components/schemas/Category'
        existing_categories:
          description: >
            is a list of categories already assigned to the subscription.
          type: array
          items:
            $ref: 'models.yaml#/components/schemas/Category'
          x-oapi-codegen-extra-tags:
            form: 'customisation.categories'
          x-go-type-skip-optional-pointer: true
    AddFeedSubscriptionRequest:
      description: contains request data for adding a new feed subscription.
      type: object
      required:
        - URL
        - feed_id
      properties:
        URL:
          $ref: 'models.yaml#/components/schemas/URL'
        feed_id:
          $ref: 'models.yaml#/components/schemas/FeedID'
    FeedSubscriptionRequest:
      description: >
        is a request to add a new feed subscription.
      type: object
      required:
        - URL
        - subscription_id
      properties:
        URL:
          description: is the URL of the feed data. Used when adding a new feed subscription.
          type: string
          x-go-name: URL
          x-oapi-codegen-extra-tags:
            form: 'url'
            validate: 'required_without=SubscriptionID,omitempty,url'
        subscription_id:
          description: is the existing subscription ID. Will be empty when adding a new feed subscription.
          type: string
          x-go-name: SubscriptionID
          x-oapi-codegen-extra-tags:
            form: 'subscription_id'
            validate: 'required_without=URL,omitempty,startswith=sub_'
        customisation:
          $ref: 'models.yaml#/components/schemas/SubscriptionCustomisation'
        settings:
          allOf:
            - $ref: 'models.yaml#/components/schemas/SubscriptionSettings'
          x-oapi-codegen-extra-tags:
            form: 'settings'
        article_filters:
          $ref: 'models.yaml#/components/schemas/SubscriptionArticleFilters'
        suggestedCategories:
          description: >
            is a list of suggested categories for the subscription.
          type: array
          items:
            $ref: 'models.yaml#/components/schemas/Category'
          x-oapi-codegen-extra-tags:
            form: '-'
            json: '-'
          x-go-type-skip-optional-pointer: true
    FeedSubscriptionResult:
      description: >
        is the result of adding a feed subscription.
      type: object
      properties:
        request:
          $ref: 'models.yaml#/components/schemas/FeedSubscriptionRequest'
        error:
          $ref: 'models.yaml#/components/schemas/APIError'
        subscription:
          $ref: 'models.yaml#/components/schemas/Subscription'
    GroupSubscriptionRequest:
      description: >
        represents a request to create a group subscription.
      type: object
      required:
        - subscriptions
      properties:
        subscription_id:
          description: >
            will be a subscription ID if the user is editing an existing group subscription.
          allOf:
            - $ref: 'models.yaml#/components/schemas/SubscriptionID'
          x-go-name: SubscriptionID
          x-oapi-codegen-extra-tags:
            json: '-'
            form: 'subscription_id'
            validate: 'omitempty,startswith=sub_'
        subscriptions:
          description: >
            contains details of the subscriptions in the group.
          x-go-type: 'map[SubscriptionID]string'
          x-oapi-codegen-extra-tags:
            form: 'subscriptions'
            validate: 'required'
        customisation:
          allOf:
            - $ref: 'models.yaml#/components/schemas/SubscriptionCustomisation'
          x-oapi-codegen-extra-tags:
            form: 'customisation'
        settings:
          allOf:
            - $ref: 'models.yaml#/components/schemas/SubscriptionSettings'
          x-oapi-codegen-extra-tags:
            form: 'settings'
        article_filters:
          $ref: 'models.yaml#/components/schemas/SubscriptionArticleFilters'
        suggestedCategories:
          description: >
            is a list of suggested categories for the subscription.
          type: array
          items:
            $ref: 'models.yaml#/components/schemas/Category'
          x-oapi-codegen-extra-tags:
            form: '-'
            json: '-'
          x-go-type-skip-optional-pointer: true
        suggestedSubscriptions:
          description: >
            is a list of suggested subscriptions for the subscription.
          x-go-type: 'Subscriptions'
          x-oapi-codegen-extra-tags:
            form: '-'
            json: '-'
          x-go-type-skip-optional-pointer: true
    AddSubscriptionToGroupRequest:
      description: >
        is a request to add a new subscription to a group subscription.
      type: object
      required:
        - suggestion_text
        - suggestions
      properties:
        suggestion_text:
          description: >
            is the name of the new subscription to add.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'suggestion_text'
            validate: 'required'
        suggestions:
          description: >
            is the subscription suggestions.
          x-go-type: 'map[SubscriptionID]string'
          x-oapi-codegen-extra-tags:
            form: 'suggestions'
        existing_subscriptions:
          description: >
            is the existing subscriptions in the group.
          x-go-type: 'map[SubscriptionID]string'
          x-oapi-codegen-extra-tags:
            form: 'subscriptions'
          x-go-type-skip-optional-pointer: true
    AddSubscriptionToSearchRequest:
      description: >
        is a request to add a new subscription to a search subscription.
      type: object
      required:
        - selected_subscription
      properties:
        selected_subscription:
          description: >
            is the name of the subscription that was selected from the suggestions.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'subscription-suggestion-text'
        suggested_subscriptions:
          description: >
            is a list of the subscription suggestions.
          x-go-type: map[SubscriptionID]string
          x-oapi-codegen-extra-tags:
            form: subscription_suggestions
          x-go-type-skip-optional-pointer: true
    ListSubscriptionsResponse:
      description: >
        contains the data retrieved and relevant for listing subscriptions.
      type: object
      required:
        - subscriptions
        - filters
        - pagination
      properties:
        subscriptions:
          description: >
            is the list of subscriptions.
          x-go-type: Subscriptions
        latest_articles:
          description: >
            is a map of the latest articles for each subscription in the result.
          x-go-type: sync.Map
        filters:
          $ref: 'models.yaml#/components/schemas/ListFilters'
        pagination:
          $ref: 'models.yaml#/components/schemas/Pagination'
    ListArticlesResponse:
      description: >
        contains the data retrieved and relevant for listing articles.
      type: object
      required:
        - articles
        - category_counts
        - filters
        - pagination
      properties:
        subscription:
          allOf:
            - $ref: 'models.yaml#/components/schemas/Subscription'
          x-go-type-skip-optional-pointer: false
        articles:
          x-go-type: Articles
          # description: >
          #   is a list of subscriptions.
          # type: array
          # items:
          #   $ref: 'models.yaml#/components/schemas/Subscription'
          # x-go-type-skip-optional-pointer: true
        filters:
          $ref: 'models.yaml#/components/schemas/ListFilters'
        pagination:
          $ref: 'models.yaml#/components/schemas/Pagination'
    SearchRequest:
      description: >
        represents a search request by the user.
      type: object
      required:
        - published_within
        - timezone
        - text
        - view
        - sort
      properties:
        subscription_id:
          description: >
            will be a subscription ID if the user has created a SearchSubscription for this request.
          allOf:
            - $ref: 'models.yaml#/components/schemas/SubscriptionID'
          x-go-name: SubscriptionID
          x-oapi-codegen-extra-tags:
            form: 'subscription_id'
            validate: 'omitzero,startswith=sub_'
        text:
          description: >
            is the text to search.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'text'
            validate: 'omitempty,required'
        categories:
          description: >
            a list of search terms for categories.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'categories'
        authors:
          description: >
            a list of search terms for authors.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'authors'
        view:
          $ref: 'models.yaml#/components/schemas/View'
        subscriptions:
          description: >
            is a list of subscription IDs.
          type: array
          items:
            $ref: 'models.yaml#/components/schemas/SubscriptionID'
          x-oapi-codegen-extra-tags:
            form: 'subscriptions'
            validate: 'omitempty,unique,dive,startswith=sub_'
          x-go-type-skip-optional-pointer: true
        published_within:
          description: >
            represents a time range within which the objects should be published
          type: string
          enum:
            - last_5mins
            - last_hour
            - last_12hours
            - last_day
            - last_week
            - last_month
            - all_time
          default: all_time
          x-oapi-codegen-extra-tags:
            form: 'published_within'
            validate: 'required,oneof=all_time last_hour last_12hours last_day last_week last_month'
        sort:
          $ref: 'models.yaml#/components/schemas/Sort'
        timezone:
          description: >
            represents the timezone of the browser (i.e., user), used for calculating published_within offset.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'timezone'
            validate: 'required,timezone'
      x-oapi-codegen-extra-tags:
        validate: 'required'
        form: 'search'
    SearchResults:
      description: >
        contains the results of a search.
      type: object
      required:
        - search
      properties:
        search:
          $ref: 'models.yaml#/components/schemas/SearchRequest'
        articles:
          x-go-type: Articles
          x-go-type-skip-optional-pointer: true
        subscriptions:
          x-go-type: Subscriptions
          x-go-type-skip-optional-pointer: true
        categories:
          description: is a list of categories.
          type: array
          items:
            $ref: 'models.yaml#/components/schemas/Category'
          x-oapi-codegen-extra-tags:
            json: 'categories'
            form: 'categories'
            validate: 'omitnil,unique,dive,url_encoded'
          x-go-type-skip-optional-pointer: true
        pagination:
          $ref: 'models.yaml#/components/schemas/Pagination'
    ExtractedMetadata:
      description: >
        contains key information about the link/site that was extracted.
      type: object
      properties:
        title:
          description: is the title of the page/link
          type: string
        author:
          description: is an author attributed to the page/link.
          type: string
        description:
          description: is a summary of the content of the page/link.
          type: string
        date:
          description: is a datestamp associated with the page/link published/updated time.
          type: string
        sitename:
          description: is the site name.
          type: string
        categories:
          description: is a list of categories associated with the page/link.
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
        tags:
          description: is a list of tags associated with the page/link.
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
    ExtractorResponse:
      description: >
        represents the response from the extractor component.
      type: object
      required:
        - url
      properties:
        url:
          $ref: 'models.yaml#/components/schemas/URL'
        format:
          description: >
            is the output format of the content field.
          type: string
          enum: ["markdown", "txt", "html", "xml", "json"]
          x-oapi-codegen-extra-tags:
            validate: 'omitempty,oneof=markdown txt html xml json'
        content:
          description: >
            is the extracted data.
          type: string
        extracted_at:
          description: >
            is a timestamp of when the content was extracted
          type: integer
        metadata:
          $ref: '#/components/schemas/ExtractedMetadata'
    ExtractorErrorResponse:
      description: >
        represents the response from the extractor when an error occurred.
      type: object
      required:
        - detail
      properties:
        detail:
          description: >
            is the summary/reason for the error.
          type: string
    AddSubscriptionFeedSuggestions:
      description: >
        contains feed suggestions details.
      type: object
      properties:
        feeds:
          description: >
            is a slice of feeds.
          x-go-type: Feeds
          x-go-type-skip-optional-pointer: true
        latest_items:
          description: >
            is a map of latest items for each suggested feed.
          x-go-type: map[FeedID]Items
          x-go-type-skip-optional-pointer: true
    AddSubscriptionYoutubeSuggestions:
      description: >
        contains Youtube suggestion details.
      type: object
      properties:
        channels:
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
    AddSubscriptionSuggestion:
      description: >
        contains data about suggestions for adding a new subscription.
      type: object
      properties:
        feed_suggestions:
          $ref: '#/components/schemas/AddSubscriptionFeedSuggestions'
        youtube_suggestions:
          $ref: '#/components/schemas/AddSubscriptionYoutubeSuggestions'
