services:
  devcontainer:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ../base/.devcontainer/alpine.Dockerfile
    volumes:
      - ..:/workspace:cached
      - /etc/localtime:/etc/localtime:ro,cached
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:rw
      - foragd-datahome:/datahome
    command: -c 'sleep infinity'
    user: vscode
    init: true
    group_add:
      - keep-groups
    cap_add:
      - SYS_PTRACE
      - SETUID
      - SETGID
    security_opt:
      - seccomp:unconfined
    hostname: devcontainer
    ports:
      - $PORT:$PORT
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc: 65535

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:$IMAGEPROXY_VERSION
    env_file:
      - .env
    environment:
      IMGPROXY_KEY: $IMGPROXY_KEY
      IMGPROXY_SALT: $IMGPROXY_SALT
      IMGPROXY_SO_REUSEPORT: "true"
      IMGPROXY_ALLOW_LOOPBACK_SOURCE_ADDRESSES: "true"
      IMGPROXY_AUTO_WEBP: "true"
      IMGPROXY_MAX_SRC_FILE_SIZE: 8000000

  googlecloud:
    image: docker.io/google/cloud-sdk:$GOOGLE_CLOUD_SDK_VERSION
    entrypoint: gcloud --quiet beta emulators pubsub start --host-port=0.0.0.0:8085 --verbosity=debug --log-http
    restart: unless-stopped

  ollama:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ../ollama.Dockerfile
    hostname: ollama
    ports:
      - 11434:11434
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc: 65535

volumes:
  foragd-datahome:
