volumes:
  es01data:
  es02data:
  es03data:
  kibanadata:
services:
  devcontainer:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /etc/localtime:/etc/localtime:ro,cached
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:rw
    command: -c 'sleep infinity'
    user: vscode
    privileged: true
    init: true
    group_add:
      - keep-groups
    cap_add:
      - SYS_PTRACE
      - SETUID
      - SETGID
    security_opt:
      - seccomp:unconfined
    hostname: devcontainer
    ports:
      - $FORAGD_SERVER_PORT:$FORAGD_SERVER_PORT
      - 6060:6060
      - 6061:6061
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc: 65535

  setup:
    env_file:
      - .env
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_STACK_VERSION
    volumes:
      - ../deployments/certs:/usr/share/elasticsearch/config/certs
    command: |
      bash -c '
              if [ x$${ELASTICSEARCH_PASSWORD} == x ]; then
          echo "Set the ELASTICSEARCH_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x$${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: es01\n"\
          "    dns:\n"\
          "      - es01\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es02\n"\
          "    dns:\n"\
          "      - es02\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es03\n"\
          "    dns:\n"\
          "      - es03\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        # echo "Setting file permissions"
        # chown -R root:root config/certs;
        # find . -type d -exec chmod 750 \{\} \;;
        # find . -type f -exec chmod 640 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:$${ELASTICSEARCH_PASSWORD:-foragd}" -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"$${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  es01:
    depends_on:
      setup:
        condition: service_healthy
    hostname: es01
    env_file:
      - .env
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_STACK_VERSION
    volumes:
      - ../deployments/certs:/usr/share/elasticsearch/config/certs
      - es01data:/usr/share/elasticsearch/data
    ports:
      - $ELASTICSEARCH_PORT:9200
    environment:
      - node.name=es01
      - cluster.name=foragd-dev
      - ELASTIC_PASSWORD=$ELASTICSEARCH_PASSWORD
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    mem_limit: $ELASTICSEARCH_MEM_LIMIT
    oom_kill_disable: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      - co.elastic.logs/module=elasticsearch
    stop_grace_period: 1m

  es02:
    depends_on:
      - es01
    hostname: es02
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_STACK_VERSION
    env_file:
      - .env
    volumes:
      - ../deployments/certs:/usr/share/elasticsearch/config/certs
      - es02data:/usr/share/elasticsearch/data
    environment:
      - node.name=es02
      - cluster.name=foragd-dev
      - ELASTIC_PASSWORD=$ELASTICSEARCH_PASSWORD
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es02/es02.key
      - xpack.security.http.ssl.certificate=certs/es02/es02.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es02/es02.key
      - xpack.security.transport.ssl.certificate=certs/es02/es02.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    mem_limit: $ELASTICSEARCH_MEM_LIMIT
    oom_kill_disable: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      - co.elastic.logs/module=elasticsearch
    stop_grace_period: 1m

  es03:
    depends_on:
      - es02
    hostname: es03
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_STACK_VERSION
    volumes:
      - ../deployments/certs:/usr/share/elasticsearch/config/certs
      - es03data:/usr/share/elasticsearch/data
    env_file:
      - .env
    environment:
      - node.name=es03
      - cluster.name=foragd-dev
      - ELASTIC_PASSWORD=$ELASTICSEARCH_PASSWORD
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es03/es03.key
      - xpack.security.http.ssl.certificate=certs/es03/es03.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es03/es03.key
      - xpack.security.transport.ssl.certificate=certs/es03/es03.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    mem_limit: $ELASTICSEARCH_MEM_LIMIT
    oom_kill_disable: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      - co.elastic.logs/module=elasticsearch
    stop_grace_period: 1m

  kibana:
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    hostname: kibana
    env_file:
      - .env
    image: docker.elastic.co/kibana/kibana:$ELASTIC_STACK_VERSION
    volumes:
      - ../deployments/certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    ports:
      - $KIBANA_PORT:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      - co.elastic.logs/module=kibana
    stop_grace_period: 1m

  # metricbeat:
  #   depends_on:
  #     es01:
  #       condition: service_healthy
  #     kibana:
  #       condition: service_healthy
  #   hostname: metricbeat
  #   image: docker.elastic.co/beats/metricbeat:$ELASTIC_STACK_VERSION
  #   restart: always
  #   user: root
  #   volumes:
  #     - ../deployments/certs:/usr/share/metricbeat/config/certs
  #     - ./data/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
  #     - ${HOST_FILESYSTEM}:/hostfs:ro
  #     - /var/run/dbus/system_bus_socket,target=/hostfs/var/run/dbus/system_bus_socket:ro
  #     - ${DOCKER_SOCK}:/var/run/docker.sock
  #   cgroup: host
  #   environment:
  #     - DBUS_SYSTEM_BUS_ADDRESS='unix:path=/hostfs/var/run/dbus/system_bus_socket'
  #     - ELASTIC_USER=elastic
  #     - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
  #   command:
  #     - --strict.perms=false

  # filebeat:
  #   depends_on:
  #     es01:
  #       condition: service_healthy
  #   image: docker.elastic.co/beats/filebeat:$ELASTIC_STACK_VERSION
  #   user: root
  #   volumes:
  #     - ../deployments/certs:/usr/share/filebeat/config/certs
  #     - ./data/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - ./data:/usr/share/filebeat/ingest_data
  #     - "../../../.local/share/containers:/var/lib/docker/containers:ro"
  #     - ${DOCKER_SOCK}:/var/run/docker.sock
  #   environment:
  #     - ELASTIC_USER=elastic
  #     - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
  #   command:
  #     - --strict.perms=false

  otel-collector:
    image: docker.io/elastic/elastic-agent:$ELASTIC_STACK_VERSION
    container_name: otel-collector
    deploy:
      resources:
        limits:
          memory: 1.5G
    restart: unless-stopped
    command: ["--config", "/etc/otelcol-config.yml"]
    # network_mode: host
    user: root
    volumes:
      - ../deployments/certs:/usr/share/elastic-agent/certs
      - ${HOST_FILESYSTEM}:/hostfs:ro
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
      - ./data/otelcol-config.yml:/etc/otelcol-config.yml
    environment:
      - HOST_FILESYSTEM
      - ELASTIC_AGENT_OTEL
      - ELASTIC_API_KEY
      - ELASTIC_ENDPOINT
      - STORAGE_DIR=/usr/share/elastic-agent

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:$IMAGEPROXY_VERSION
    environment:
      IMGPROXY_KEY: 7c3e9eecb5f62436587d86aba82b16a1efcbcaa95469e9923a72822bcacb284d77bd16f1427e20693733c5f24fadfb2c468dabe533d94152006f04e8121080b2
      IMGPROXY_SALT: d94a9bf2767e97c0d28e6514b3ebfb2a6eb82e0929bc0d028df93bf337ce99899f9077edf4dfc67c57fdee1c50a1f9f860277930725234d6c814ab0c66712d2f
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_USE_LAST_MODIFIED: "true"
      IMGPROXY_CACHE_CONTROL_PASSTHROUGH: "true"
      IMGPROXY_SO_REUSEPORT: "true"
      IMGPROXY_ALLOW_LOOPBACK_SOURCE_ADDRESSES: "true"
      IMGPROXY_AUTO_WEBP: "true"
      IMGPROXY_MAX_SRC_FILE_SIZE: 8000000

  googlecloud:
    image: docker.io/google/cloud-sdk:$GOOGLE_CLOUD_SDK_VERSION
    entrypoint: gcloud --quiet beta emulators pubsub start --host-port=0.0.0.0:8085 --verbosity=debug --log-http
    restart: unless-stopped
