volumes:
  es01data:
  es02data:
  es03data:
  kibanadata:
services:
  devcontainer:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /etc/localtime:/etc/localtime:ro,cached
    command: -c 'sleep infinity'
    user: vscode
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    hostname: devcontainer
    ports:
      - $GOFEEDME_SERVER_PORT:$GOFEEDME_SERVER_PORT
  stepca:
    env_file:
      - .env
    hostname: stepca
    image: docker.io/smallstep/step-ca
    restart: always
    volumes:
      - ../deployments/stepca:/home/step
    environment:
      - DOCKER_STEPCA_INIT_NAME=GOFEEDME
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,stepca
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_PASSWORD=$DOCKER_STEPCA_INIT_PASSWORD
    ports:
      - $STEPCA_PORT:9000
  setup:
    env_file:
      - .env
    image: docker.elastic.co/elasticsearch/elasticsearch:$STACK_VERSION
    volumes:
      - ../deployments/certs:/usr/share/elasticsearch/config/certs
    command: |
      bash -c '
              if [ x$${ELASTIC_PASSWORD:-gofeedme} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x$${KIBANA_PASSWORD:-gofeedme} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: es01\n"\
          "    dns:\n"\
          "      - es01\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es02\n"\
          "    dns:\n"\
          "      - es02\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es03\n"\
          "    dns:\n"\
          "      - es03\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        # echo "Setting file permissions"
        # chown -R root:root config/certs;
        # find . -type d -exec chmod 750 \{\} \;;
        # find . -type f -exec chmod 640 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:$${ELASTIC_PASSWORD:-gofeedme}" -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"$${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: ['CMD-SHELL', '[ -f config/certs/es01/es01.crt ]']
      interval: 1s
      timeout: 5s
      retries: 120

  es01:
    depends_on:
      setup:
        condition: service_healthy
    hostname: es01
    env_file:
      - .env
    image: docker.elastic.co/elasticsearch/elasticsearch:$STACK_VERSION
    volumes:
      - ../deployments/certs:/usr/share/elasticsearch/config/certs
      - ../deployments/elasticsearch/es01/logs:/usr/share/elasticsearch/logs
      - es01data:/usr/share/elasticsearch/data
    ports:
      - $ES_PORT:9200
    environment:
      - node.name=es01
      - cluster.name=$CLUSTER_NAME
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
      - cluster.routing.allocation.disk.watermark.low=0.95
      - cluster.routing.allocation.disk.watermark.high=0.98
      - cluster.routing.allocation.disk.watermark.flood_stage=0.99
    mem_limit: $ES_MEM_LIMIT
    oom_kill_disable: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      - co.elastic.logs/module=elasticsearch

  es02:
    depends_on:
      - es01
    hostname: es02
    image: docker.elastic.co/elasticsearch/elasticsearch:$STACK_VERSION
    env_file:
      - .env
    volumes:
      - ../deployments/certs:/usr/share/elasticsearch/config/certs
      - ../deployments/elasticsearch/es02/logs:/usr/share/elasticsearch/logs
      - es02data:/usr/share/elasticsearch/data
    environment:
      - node.name=es02
      - cluster.name=$CLUSTER_NAME
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es02/es02.key
      - xpack.security.http.ssl.certificate=certs/es02/es02.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es02/es02.key
      - xpack.security.transport.ssl.certificate=certs/es02/es02.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
      - cluster.routing.allocation.disk.watermark.low=0.95
      - cluster.routing.allocation.disk.watermark.high=0.98
      - cluster.routing.allocation.disk.watermark.flood_stage=0.99
    mem_limit: $ES_MEM_LIMIT
    oom_kill_disable: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      - co.elastic.logs/module=elasticsearch

  es03:
    depends_on:
      - es02
    hostname: es03
    image: docker.elastic.co/elasticsearch/elasticsearch:$STACK_VERSION
    volumes:
      - ../deployments/certs:/usr/share/elasticsearch/config/certs
      - ../deployments/elasticsearch/es03/logs:/usr/share/elasticsearch/logs
      - es03data:/usr/share/elasticsearch/data
    env_file:
      - .env
    environment:
      - node.name=es03
      - cluster.name=$CLUSTER_NAME
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es03/es03.key
      - xpack.security.http.ssl.certificate=certs/es03/es03.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es03/es03.key
      - xpack.security.transport.ssl.certificate=certs/es03/es03.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
      - cluster.routing.allocation.disk.watermark.low=0.95
      - cluster.routing.allocation.disk.watermark.high=0.98
      - cluster.routing.allocation.disk.watermark.flood_stage=0.99
    mem_limit: $ES_MEM_LIMIT
    oom_kill_disable: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      - co.elastic.logs/module=elasticsearch

  kibana:
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    hostname: kibana
    env_file:
      - .env
    image: docker.elastic.co/kibana/kibana:$STACK_VERSION
    volumes:
      - ../deployments/certs:/usr/share/kibana/config/certs
      - ../deployments/kibana/logs:/usr/share/kibana/logs
      - kibanadata:/usr/share/kibana/data
    ports:
      - $KIBANA_PORT:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      - co.elastic.logs/module=kibana
  metricbeat:
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    hostname: metricbeat
    image: docker.elastic.co/beats/metricbeat:$STACK_VERSION
    restart: always
    volumes:
      - ../deployments/certs:/usr/share/metricbeat/config/certs
      - ../deployments/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - /var/run/dbus/system_bus_socket,target=/hostfs/var/run/dbus/system_bus_socket:ro
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    environment:
      - output.elasticsearch.hosts=["es01:9200"]
      - DBUS_SYSTEM_BUS_ADDRESS='unix:path=/hostfs/var/run/dbus/system_bus_socket'
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
