# Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.
# SPDX-License-Identifier: 	AGPL-3.0-or-later

openapi: '3.0.3'
info:
  version: 1.0.0
  title: Common API
  description: Common API objects and fields.
paths: {}
components:
  schemas:
    Action:
      description: >
        defines an operation to change the state of objects.
      type: string
      enum: ['read', 'unread', 'save', 'remove', 'edit']
      x-oapi-codegen-extra-tags:
        validate: 'oneof=read unread save remove edit'
    Count:
      description: >
        is the count of items to retrieve with a request.
      type: string
      default: '10'
      x-oapi-codegen-extra-tags:
        form: 'count'
        validate: 'numeric,gt=0,lt=20'
    View:
      description: >
        The state of objects to view.
      type: string
      enum: ['read', 'unread', 'all']
      default: 'unread'
      x-oapi-codegen-extra-tags:
        validate: 'oneof=read unread all'
        form: 'view'
    Pagination:
      description: contains data for paginating through results.
      type: string
      x-oapi-codegen-extra-tags:
        form: 'pagination'
        validate: 'omitempty,url_encoded'
    SortBy:
      description: >
        represents the selected field to sort on.
      type: string
      enum: ['unread_count', 'last_updated']
      x-oapi-codegen-extra-tags:
        validate: 'oneof=unread_count last_updated'
        form: 'sort_by'
    SortOrder:
      description: >
        represents the order for sorting the selected field.
      type: string
      enum: ['asc', 'desc']
      x-oapi-codegen-extra-tags:
        validate: 'oneof=asc desc'
        form: 'sort_order'
    Sort:
      description: contains information on sorting objects.
      type: object
      required:
        - sort_by
        - sort_order
      properties:
        sort_by:
          $ref: '#/components/schemas/SortBy'
        sort_order:
          $ref: '#/components/schemas/SortOrder'
      x-oapi-codegen-extra-tags:
        json: 'sort'
    CommonFilters:
      description: >
        contains filter parameters that are common across all requests.
      type: object
      required:
        - view
        - count
        - sort_by
        - sort_order
      properties:
        count:
          $ref: '#/components/schemas/Count'
        view:
          $ref: '#/components/schemas/View'
        sort_by:
          $ref: '#/components/schemas/SortBy'
        sort_order:
          $ref: '#/components/schemas/SortOrder'
    SubscriptionFilters:
      description: >
        contains filter parameters that apply to subscriptions.
      type: object
      allOf:
        - $ref: '#/components/schemas/CommonFilters'
        - type: object
          properties:
            subscriptions:
              description: >
                is a list of subscription IDs.
              type: array
              items:
                $ref: 'models.yaml#/components/schemas/SubscriptionID'
              x-oapi-codegen-extra-tags:
                json: 'subscriptions'
                form: 'subscriptions'
                validate: 'omitnil,unique,dive,startswith=sub_'
              x-go-type-skip-optional-pointer: true
            pagination:
              $ref: '#/components/schemas/Pagination'
            categories:
              description: is a list of categories.
              type: array
              items:
                $ref: 'models.yaml#/components/schemas/Category'
              x-oapi-codegen-extra-tags:
                json: 'categories'
                form: 'categories'
                validate: 'omitnil,unique,dive,url_encoded'
              x-go-type-skip-optional-pointer: true
    ArticleFilters:
      description: >
        contains filter parameters that apply to articles.
      type: object
      allOf:
        - $ref: '#/components/schemas/SubscriptionFilters'
        - type: object
          properties:
            articles:
              description: >
                is a list of item IDs.
              type: array
              items:
                $ref: 'models.yaml#/components/schemas/ItemID'
              x-oapi-codegen-extra-tags:
                json: 'articles'
                form: 'articles[]'
                validate: 'omitnil,unique,dive,startswith=item_'
              x-go-type-skip-optional-pointer: true
    UserConfirmation:
      description: >
        indicates the user's decision for a (usually) destructive action.
      type: string
      enum: ['yes', 'no', 'cancel']
      default: 'no'
      x-go-type-skip-optional-pointer: true
      x-oapi-codegen-extra-tags:
        form: 'confirmation'
        validate: 'required,oneof=yes no cancel'
    UserSignupRequest:
      description: >
        contains the details for a user signup request.
      type: object
      required:
        - email
        - password
      properties:
        nickname:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'omitempty'
            form: 'nickname,omitempty'
          x-go-type-skip-optional-pointer: true
        email:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,email'
            form: 'email'
        password:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=10'
            form: 'password'
        msg:
          $ref: '#/components/schemas/UserMessage'
    ImportSource:
      description: >
        defines the source that will be used for an import.
      type: string
      enum: ['opml_file', 'opml_url', 'url_list']
      x-enum-varnames: ['OPMLFile', 'OPMLURL', 'URLs']
      x-oapi-codegen-extra-tags:
        json: 'source'
        form: 'source'
        validate: 'oneof=opml_file opml_url url_list'
    SubscriptionEdit:
      description: >
        represents subscription details for editing by the user.
      type: object
      allOf:
        - $ref: 'models.yaml#/components/schemas/ObjectCustomisation'
        - type: object
          required:
            - subscription_id
          properties:
            subscription_id:
              $ref: 'models.yaml#/components/schemas/SubscriptionID'
    SubscriptionRequest:
      description: >
        represents a request to create a subscription.
      type: object
      required:
        - URL
      properties:
        URL:
          description: is the URL of the feed data.
          type: string
          x-go-name: URL
          x-oapi-codegen-extra-tags:
            form: 'url'
            validate: 'required,url'
        nickname:
          description: a custom name for the subscription. Overrides the feed name.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'user_nickname'
        categories:
          description: a list  custom categories for the subscription. Combined with the feed's own categories.
          type: array
          items:
            $ref: 'models.yaml#/components/schemas/Category'
          x-go-type-skip-optional-pointer: true
          x-oapi-codegen-extra-tags:
            form: 'user_categories[]'
    MarkSubscriptionsRequest:
      description: >
        represents a user request for marking a subscription or collection of subscriptions as read or unread.
      type: object
      required:
        - subscriptions
      properties:
        subscriptions:
          description: >
            is a list of subscription IDs.
          type: array
          items:
            $ref: 'models.yaml#/components/schemas/SubscriptionID'
          x-oapi-codegen-extra-tags:
            json: 'subscriptions'
            form: 'subscriptions'
            validate: 'omitnil,unique,dive,startswith=sub_'
          x-go-type-skip-optional-pointer: true
        redirect:
          $ref: '#/components/schemas/Redirect'
    RemoveSubscriptionsRequest:
      description: >
        represents a user request for unsubscribing from subscriptions.
      type: object
      required:
        - subscriptions
        - confirmation
      properties:
        subscriptions:
          description: >
            is a list of subscription IDs.
          type: array
          items:
            $ref: 'models.yaml#/components/schemas/SubscriptionID'
          x-oapi-codegen-extra-tags:
            json: 'subscriptions'
            form: 'subscriptions'
            validate: 'omitnil,unique,dive,startswith=sub_'
          x-go-type-skip-optional-pointer: true
        confirmation:
          $ref: '#/components/schemas/UserConfirmation'
    MarkArticlesRequest:
      description: >
        represents a user request for marking a collection of articles as read or unread.
      type: object
      required:
        - articles
      properties:
        articles:
          description: >
            is a list of articles by subscription.
          type: array
          items:
            type: string
          x-oapi-codegen-extra-tags:
            json: 'articles'
            form: 'articles'
            validate: 'omitnil,unique'
          x-go-type-skip-optional-pointer: true
        redirect:
          $ref: '#/components/schemas/Redirect'
    SearchRequest:
      description: >
        represents a search request by the user.
      type: object
      required:
        - text
      properties:
        text:
          description: >
            is the text to search.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'text'
            validate: 'required'
    UserMessage:
      description: >
        represents a message that can be displayed to the user as the result of an action.
      type: object
      required:
        - summary
        - status
      properties:
        summary:
          description: >
            is a user-level brief description for the message, which can be used as a title
            or summary.
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required'
        details:
          description: >
            is a longer description and/or background details about the message.
          type: string
        status:
          description: >
            indicates the severity or importance of the message.
          type: string
          enum: ['info', 'success', 'warning', 'error']
          x-oapi-codegen-extra-tags:
            validate: 'required'
    Response:
      description: >
        is a response from the backend or a component in the backend.
      type: object
      required:
        - status_code
      properties:
        status_code:
          description: >
            is a status code, typically a HTTP response code.
          type: integer
          default: 200
        internal_error:
          description: >
            is any error that is associated with the message.
          x-go-type: error
          x-go-type-skip-optional-pointer: true
          x-oapi-codegen-extra-tags:
            json: '-'
    Redirect:
      description: >
        specifies a location to which the client should be redirected on a successful request. Used to perform a
        client-side redirection with htmx.
      type: string
      x-oapi-codegen-extra-tags:
        form: 'redirect'
