# Copyright 2024 Joshua Rich <joshua.rich@gmail.com>.
# SPDX-License-Identifier: 	AGPL-3.0-or-later

openapi: '3.0.3'
info:
  version: 1.0.0
  title: Common Models
  description: Common objects and fields.
paths: {}
components:
  schemas:
    # Common Fields.
    Timestamp:
      description: is when the document was created.
      x-go-type: 'time.Time'
      x-oapi-codegen-extra-tags:
        json: '@timestamp'
        validate: 'required'
    CreatedAt:
      description: records when the object was created in the database.
      x-go-type: 'time.Time'
      x-oapi-codegen-extra-tags:
        json: 'created_at'
        validate: 'required'
    UpdatedAt:
      description: records when the object was last updated in the database.
      x-go-type: 'time.Time'
      x-oapi-codegen-extra-tags:
        json: 'updated_at,omitempty'
        validate: 'omitnil'
    DeletedAt:
      description: records when the object was deleted.
      x-go-type: 'time.Time'
      x-oapi-codegen-extra-tags:
        json: 'deleted_at,omitempty'
        validate: 'omitnil'
      deprecated: true
    URL: &URL
      description: is a URL.
      type: string
      x-go-name: URL
      x-oapi-codegen-extra-tags:
        validate: 'url'
        json: 'url'
    Mark:
      description: >
        applies the given mark action to objects.
      type: string
      enum: ['read', 'unread']
      x-oapi-codegen-extra-tags:
        form: 'mark'
        validate: 'oneof=read unread'
    State:
      description: >
        Tracks the state of an object.
      type: string
      enum: ['read', 'unread', 'saved']
      default: 'unread'
      x-oapi-codegen-extra-tags:
        json: 'state'
        validate: 'oneof=read unread saved'
    HTMLString:
      description: is a string that can contain HTML.
      type: string
      x-go-type-skip-optional-pointer: true
      x-oapi-codegen-extra-tags:
        validate: 'url_encoded'
    FeedID:
      description: is the unique ID of a feed.
      type: string
      x-go-name: FeedID
      x-oapi-codegen-extra-tags:
        validate: 'required,startswith=feed_'
        json: 'feed_id'
        form: 'feed_id'
    ItemID:
      description: is the unique ID of an item.
      type: string
      x-go-name: ItemID
      x-oapi-codegen-extra-tags:
        validate: 'required,startswith=item_'
        json: 'item_id'
        form: 'item_id'
    SubscriptionID:
      description: is the unique ID of a subscription.
      type: string
      x-go-name: SubscriptionID
      x-oapi-codegen-extra-tags:
        validate: 'required,startswith=sub_'
        json: 'subscription_id'
        form: 'subscription_id'
    UserID:
      description: is the unique ID of a user.
      type: string
      x-go-name: UserID
      x-oapi-codegen-extra-tags:
        json: 'user_id'
        validate: 'required'
        form: 'user_id'
    Category:
      description: >
        represents a taxonomy applied to an object.
      type: string
    CategoryCount:
      description: >
        holds a category and the count of its occurence. The count will be
        contextual. i.e., across subscriptions, items, etc.
      type: object
      required:
        - category
        - count
      properties:
        category:
          $ref: '#/components/schemas/Category'
        count:
          type: integer
          minimum: 0
    Timestamps:
      description: contains common (metadata) fields for database objects.
      type: object
      required:
        - created_at
      properties:
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'
    # Objects.
    User:
      description: is a user of the application.
      type: object
      allOf:
        - $ref: '#/components/schemas/Timestamps'
        - type: object
          required:
            - user_id
            - external_user_id
            - provider
            - max_history
          properties:
            user_id:
              $ref: '#/components/schemas/UserID'
            external_user_id:
              description: >
                is the ID of the user on the external backend that was used to create the account.
              type: string
              x-oapi-codegen-extra-tags:
                validate: 'required'
            provider:
              description: >
                is the backend provider that was used to create the account.
              x-oapi-codegen-extra-tags:
                validate: 'required'
            max_history:
              description: >
                is a duration representing the maximum time-frame over which objects contained within are available.
              type: string
              x-oapi-codegen-extra-tags:
                validate: 'required'
            settings:
              $ref: '#/components/schemas/UserSettings'
            subscriptions:
              description: >
                is a list of the states of all subscriptions the user has.
              type: array
              items:
                $ref: '#/components/schemas/SubscriptionFeedRelation'
              x-go-type-skip-optional-pointer: true
            favourites:
              description: >
                is a list of objects the user has marked as a favourite.
              type: array
              items:
                $ref: '#/components/schemas/Favourite'
              x-go-type-skip-optional-pointer: true
    UserSettings:
      description: >
        contains user-specific settings for the application.
      type: object
      properties:
        theme:
          description: >
            the user interface theme chosen by the user.
          type: string
          default: dracula
          x-go-type-skip-optional-pointer: true
    Favourite:
      description: >
        is an object that the user has marked as a favourite. Favourites  have higher visibility in the display and
        score higher in search results.
      type: object
      required:
        - id
        - type
        - link
        - name
      properties:
        id:
          description: >
            is a unique identifier that allows comparison of favourites.
          type: string
          x-go-name: ID
        type:
          description: >
            is the type of favourite.
          type: string
          enum:
            [
              'subscription',
              'article',
              'subscription_category',
              'article_category',
              'search',
            ]
        name:
          description: >
            is a friendly name for the link.
          type: string
        link:
          description: >
            is the internal link to the favourited object.
          x-go-type: 'json.RawMessage'
    UserSession:
      description: tracks a user session.
      type: object
      required:
        - token
        - data
        - expiry
      properties:
        token:
          description: the session token for the user.
          type: string
        data:
          description: the encoded session data.
          x-go-type: '[]byte'
        expiry:
          description: the time at which this session token expires.
          x-go-type: time.Time
    ObjectState:
      description: >
        tracks the state of an object.
      type: object
      required:
        - read
        - starred
      properties:
        read:
          description: >
            indicates whether the object has been read (true) or is unread (false).
          type: boolean
        starred:
          description: >
            indicates whether the object has been starred (true) or not (false).
          type: boolean
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'
    ObjectTimestamps:
      description: >
        contains timestamps for objects.
      type: object
      required:
        - published
      properties:
        published:
          description: >
            is the datetime at which the feed or item was published.
          x-go-type: time.Time
        updated:
          description: >
            is the datetime at which the feed or item was updated.
          x-go-type: time.Time
          x-go-type-skip-optional-pointer: true
    ObjectCommon:
      description: contains common fields across objects.
      type: object
      required:
        - source_type
        - title
        - description
      properties:
        source_type:
          description: >
            indicates what type of source the object came from.
          type: string
          enum: ['RSS', 'Atom', 'JSONFeed']
        title:
          description: >
            is the title of the feed or item.
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required'
        description:
          description: >
            is a short summary or description of the feed or item.
          type: string
        url:
          description: >
            is the URL to the webpage for the feed or item. For a feed, this is most likely the webpage the feed is
            sourced from. For an item, this is most likely the webpage containing the full item contents.
          type: string
          x-go-name: URL
          x-oapi-codegen-extra-tags:
            validate: 'omitempty,url'
          x-go-type-skip-optional-pointer: true
        categories:
          description: >
            is a list of categories that define a taxonomy for the feed or item.
          type: array
          items:
            $ref: '#/components/schemas/Category'
          x-oapi-codegen-extra-tags:
            validate: 'omitempty,unique'
          x-go-type-skip-optional-pointer: true
        authors:
          description: >
            is a list of people (names, nicknames and/or emails) who "authored" the object content.
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
        contributors:
          description: >
            is a list of people (names, nicknames and/or emails) who "contributed" the object content.
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
        image:
          $ref: '../models/feeds/types.yaml#/components/schemas/Image'
        language:
          type: string
          x-go-type-skip-optional-pointer: true
        copyright:
          type: string
          x-go-type-skip-optional-pointer: true
    ObjectCustomisation:
      description: >
        contains object fields that can be customised (overridden) by a user
      type: object
      properties:
        title:
          description: >
            is a friendly name or nickname for an object.
          type: string
          x-oapi-codegen-extra-tags:
            form: 'user_nickname'
            validate: 'omitempty'
          x-go-type-skip-optional-pointer: true
        categories:
          description: >
            is a custom list of categories for an object.
          type: array
          items:
            $ref: '#/components/schemas/Category'
          x-oapi-codegen-extra-tags:
            form: 'user_categories'
            validate: 'omitempty,unique'
          x-go-type-skip-optional-pointer: true
    Feed:
      description: represents a feed object.
      type: object
      allOf:
        - $ref: '#/components/schemas/ObjectCommon'
        - $ref: '#/components/schemas/ObjectTimestamps'
        - type: object
          required:
            - feed_id
            - source_url
            - created_at
          properties:
            feed_id:
              $ref: '#/components/schemas/FeedID'
            source_url:
              description: >
                is a URL to the source Feed document.
              allOf:
                - $ref: '#/components/schemas/URL'
              x-go-name: SourceURL
              x-oapi-codegen-extra-tags:
                validate: 'required,url'
            created_at:
              $ref: '#/components/schemas/CreatedAt'
    Item:
      description: represents an individual item (e.g., an individual feed item).
      type: object
      allOf:
        - $ref: '#/components/schemas/ObjectCommon'
        - $ref: '#/components/schemas/ObjectTimestamps'
        - type: object
          required:
            - item_id
            - feed_id
            - feed_title
            - Timestamp
          properties:
            Timestamp:
              $ref: '#/components/schemas/Timestamp'
            item_id:
              $ref: '#/components/schemas/ItemID'
            feed_id:
              $ref: '#/components/schemas/FeedID'
            feed_title:
              description: >
                is the title of the feed to which this item belongs.
              type: string
              x-oapi-codegen-extra-tags:
                validate: 'required'
            content:
              description: >
                contains the item content.
              type: string
              x-go-type-skip-optional-pointer: true
    SubscriptionFeedRelation:
      description: >
        links the IDs of a subscription and a feed.
      type: object
      required:
        - subscription_id
        - feed_id
      properties:
        subscription_id:
          $ref: '#/components/schemas/SubscriptionID'
        feed_id:
          $ref: '#/components/schemas/FeedID'
    UserSubscriptionFeedRelation:
      description: >
        links the IDs of a user to their subscriptions.
      type: object
      allOf:
        - $ref: '#/components/schemas/SubscriptionFeedRelation'
        - type: object
          required:
            - user_id
          properties:
            user_id:
              $ref: '#/components/schemas/UserID'
    SubscriptionState:
      description: >
        contains the data that represents the state and customisation applied to a user subscription.
      type: object
      allOf:
        - $ref: '#/components/schemas/Timestamps'
        - $ref: '#/components/schemas/UserSubscriptionFeedRelation'
        - type: object
          required:
            - state
          properties:
            state:
              $ref: '#/components/schemas/ObjectState'
            customisation:
              $ref: '#/components/schemas/ObjectCustomisation'
            item_states:
              description: >
                contains the states of items marked explicitly as read/unread/saved by the user.
              x-go-type: 'map[ItemID]ObjectState'
              x-go-type-skip-optional-pointer: true
    Subscription:
      description: >
        represents a feed a user has subscribed to.
      type: object
      properties:
        state:
          $ref: '#/components/schemas/SubscriptionState'
        feed:
          $ref: '#/components/schemas/Feed'
        unread_count:
          description: >
            is the value of items that are not explicitly marked unread by the user for this subscription.
            Calculated dynamically at runtime.
          type: integer
          x-go-type-skip-optional-pointer: true
          x-oapi-codegen-extra-tags:
            json: '-'
            validate: 'gte=0'
    Article:
      description: >
        is the representation of an item from the user's perspective. It holds the original item and additional fields
        to track the state of the item from the perspective of the user.
      type: object
      required:
        - subscription_id
      properties:
        item:
          $ref: '#/components/schemas/Item'
        subscription_id:
          $ref: '#/components/schemas/SubscriptionID'
        subscription_customisation:
          $ref: '#/components/schemas/ObjectCustomisation'
        state:
          $ref: '#/components/schemas/ObjectState'
