[[file]]
path = "feeds-vs-social-media"
file = "feeds-vs-social-media.md"

[[file]]
path = "finding-feeds"
file = "finding-feeds.md"

[[file]]
path = "managing-feed-overload"
file = "managing-feed-overload.md"

[[file]]
path = "foragd-vs-inoreader-vs-feedly"
file = "foragd-vs-inoreader-vs-feedly.md"

[[file]]
path = "rediscovering-the-indie-web"
file = "rediscovering-the-indie-web.md"

[[file]]
path = "article-filtering-in-foragd"
file = "article-filtering-in-foragd.md"
