# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/schemas/v3.0/schema.yaml
# Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.
openapi: "3.0.3"
info:
  version: 1.0.0
  title: Feeds Abstraction
  description: >
    Provides an astraction layer across different types of feed specifications.
  license:
    name: AGPL-3.0-or-later
    url: https://spdx.org/licenses/AGPL-3.0-only.html
paths: {}
components:
  schemas:
