# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/schemas/v3.0/schema.yaml

# Copyright 2024 Joshua Rich <joshua.rich@gmail.com>.
# SPDX-License-Identifier: 	AGPL-3.0-or-later

openapi: "3.0.3"
info:
  version: 1.0.0
  title: Common Models
  description: Common objects and fields.
paths: {}
components:
  schemas:
    # Common Fields.
    Timestamp:
      description: is when the document was created.
      x-go-type: "time.Time"
      x-oapi-codegen-extra-tags:
        json: "@timestamp"
        validate: "required"
    CreatedAt:
      description: records when the object was created in the database.
      x-go-type: "time.Time"
      x-oapi-codegen-extra-tags:
        json: "created_at"
        validate: "required"
    UpdatedAt:
      description: records when the object was last updated in the database.
      x-go-type: "time.Time"
      x-oapi-codegen-extra-tags:
        json: "updated_at,omitempty"
        validate: "omitnil"
    DeletedAt:
      description: records when the object was deleted.
      x-go-type: "time.Time"
      x-oapi-codegen-extra-tags:
        json: "deleted_at,omitempty"
        validate: "omitnil"
    URL: &URL
      description: is a URL.
      type: string
      x-go-name: URL
      x-oapi-codegen-extra-tags:
        validate: "url"
        json: "url"
    Mark:
      description: >
        applies the given mark action to objects.
      type: string
      enum: ["read", "unread"]
      x-oapi-codegen-extra-tags:
        form: "mark"
        validate: "oneof=read unread"
    State:
      description: >
        Tracks the state of an object.
      type: string
      enum: ["read", "unread", "saved"]
      default: "unread"
      x-oapi-codegen-extra-tags:
        json: "state"
        validate: "oneof=read unread saved"
    HTMLString:
      description: is a string that can contain HTML.
      type: string
      x-go-type-skip-optional-pointer: true
      x-oapi-codegen-extra-tags:
        validate: "url_encoded"
    FeedID:
      description: is the unique ID of a feed.
      type: string
      x-go-name: FeedID
      x-oapi-codegen-extra-tags:
        validate: "required,startswith=feed_"
        json: "feed_id"
        form: "feed_id"
    ItemID:
      description: is the unique ID of an item.
      type: string
      x-go-name: ItemID
      x-oapi-codegen-extra-tags:
        validate: "required,startswith=item_"
        json: "item_id"
        form: "feed_id"
    SubscriptionID:
      description: is the unique ID of a subscription.
      type: string
      x-go-name: SubscriptionID
      x-oapi-codegen-extra-tags:
        validate: "required,startswith=sub_"
        form: "subscription_id"
        json: "subscription_id"
    ItemState:
      description: >
        contains the user state for the item.
      type: object
      required:
        - item_id
        - state
      properties:
        item_id:
          $ref: "#/components/schemas/ItemID"
        state:
          $ref: "#/components/schemas/State"
      x-oapi-codegen-extra-tags:
        json: "-"
    UserID:
      description: is the unique ID of a user.
      type: string
      x-go-name: UserID
      x-oapi-codegen-extra-tags:
        json: "user_id"
        validate: "required"
    Category:
      description: >
        represents a taxonomy applied to an object.
      type: string
    CategoryCount:
      description: >
        holds a category and the count of its occurence. The count will be
        contextual. i.e., across subscriptions, items, etc.
      type: object
      required:
        - category
        - count
      properties:
        category:
          $ref: "#/components/schemas/Category"
        count:
          type: integer
          minimum: 0
    Timestamps:
      description: contains common (metadata) fields for database objects.
      type: object
      required:
        - created_at
      properties:
        created_at:
          $ref: "#/components/schemas/CreatedAt"
        updated_at:
          $ref: "#/components/schemas/UpdatedAt"
    # Objects.
    User:
      description: is a user of the application.
      type: object
      allOf:
        - $ref: "#/components/schemas/Timestamps"
        - type: object
          required:
            - user_id
            - max_history
          properties:
            user_id:
              $ref: "#/components/schemas/UserID"
            max_history:
              description: >
                Represents the maximum time-frame over which the user
                can view items.
              type: string
            subscriptions:
              description: >
                is the list of subscriptions for the user.
              x-go-type: "[]*Subscription"
              # type: array
              # items:
              #   allOf:
              #     - $ref: "#/components/schemas/Subscription"
              x-go-type-skip-optional-pointer: true
    ObjectCommon:
      description: contains common fields across objects.
      type: object
      required:
        - source_type
        - title
        - description
        - url
        - published
      properties:
        source_type:
          description: >
            indicates what type of source the object came from.
          type: string
          enum: ["RSS","Atom","JSONFeed"]
        title:
          description: >
            is the title of the feed or item.
          type: string
          x-oapi-codegen-extra-tags:
            validate: "required"
        description:
          description: >
            is a short summary or description of the feed or item.
          type: string
        url:
          description: >
            is the URL to the webpage for the feed or item. For a feed, this is most likely the webpage the feed is
            sourced from. For an item, this is most likely the webpage containing the full item contents.
          type: string
          x-go-name: URL
          x-oapi-codegen-extra-tags:
            validate: "required,url"
        published:
          description: >
            is the datetime at which the feed or item was published.
          x-go-type: time.Time
        updated:
          description: >
            is the datetime at which the feed or item was updated.
          x-go-type: time.Time
          x-go-type-skip-optional-pointer: true
        categories:
          description: >
            is a list of categories that define a taxonomy for the feed or item.
          type: array
          items:
            $ref: "#/components/schemas/Category"
          x-oapi-codegen-extra-tags:
            validate: "omitempty,unique"
          x-go-type-skip-optional-pointer: true
        authors:
          description: >
            is a list of people (names, nicknames and/or emails) who "authored" the object content.
          type: array
          items:
            type: string
          x-oapi-codegen-extra-tags:
            validate: "omitempty,unique"
          x-go-type-skip-optional-pointer: true
        contributors:
          description: >
            is a list of people (names, nicknames and/or emails) who "contributed" the object content.
          type: array
          items:
            type: string
          x-oapi-codegen-extra-tags:
            validate: "omitempty,unique"
          x-go-type-skip-optional-pointer: true
        image:
          $ref: "../pkg/feeds/types.yaml#/components/schemas/Image"
        language:
          type: string
          x-go-type-skip-optional-pointer: true
        copyright:
          type: string
          x-go-type-skip-optional-pointer: true
    Tokens:
      type: object
      required:
        - IDToken
        - Claims
        - AccessToken
      properties:
        IDToken:
          x-go-type: "*oidc.IDToken"
          x-go-type-import:
            path: github.com/coreos/go-oidc
        Claims:
          type: object
          $ref: "#/components/schemas/Claims"
        AccessToken:
          type: string
    Claims:
      type: object
      properties:
        Subject:
          type: string
          x-oapi-codegen-extra-tags:
            json: "sub"
          x-go-type-skip-optional-pointer: true
        SessionID:
          type: string
          x-oapi-codegen-extra-tags:
            json: "sid"
          x-go-type-skip-optional-pointer: true
        UserName:
          type: string
          x-oapi-codegen-extra-tags:
            json: "name"
          x-go-type-skip-optional-pointer: true
        UserPictureURL:
          type: string
          x-oapi-codegen-extra-tags:
            json: "picture"
          x-go-type-skip-optional-pointer: true
        Issuer:
          type: string
          x-oapi-codegen-extra-tags:
            json: "iss"
          x-go-type-skip-optional-pointer: true
        UserNickName:
          type: string
          x-oapi-codegen-extra-tags:
            json: "nickname"
          x-go-type-skip-optional-pointer: true
        UpdatedAt:
          # x-go-type: 'time.Time'
          # type: string
          x-oapi-codegen-extra-tags:
            json: "updated_at"
          x-go-type-skip-optional-pointer: true
        Audience:
          type: string
          x-oapi-codegen-extra-tags:
            json: "aud"
          x-go-type-skip-optional-pointer: true
        Expiry:
          # x-go-type: 'time.Time'
          type: integer
          x-oapi-codegen-extra-tags:
            json: "exp"
          x-go-type-skip-optional-pointer: true
        IssuedAt:
          # x-go-type: 'time.Time'
          type: integer
          x-oapi-codegen-extra-tags:
            json: "iat"
          x-go-type-skip-optional-pointer: true
    UserSession:
      description: tracks a user session.
      type: object
      required:
        - token
        - data
        - expiry
      properties:
        token:
          description: the session token for the user.
          type: string
        data:
          description: the encoded session data.
          x-go-type: "[]byte"
        expiry:
          description: the time at which this session token expires.
          x-go-type: time.Time
    SubscriptionCustomisation:
      description: >
        represents the properties of a subscription a user can customize.
      type: object
      properties:
        user_nickname:
          description: >
            is a friendly name or nickname for the feed given by the user.
          type: string
          x-oapi-codegen-extra-tags:
            form: "user_nickname"
            validate: "omitempty"
          x-go-type-skip-optional-pointer: true
        user_categories:
          description: >
            is a user-defined list of Category names for the subscription.
          type: array
          items:
            $ref: "#/components/schemas/Category"
          x-oapi-codegen-extra-tags:
            json: "user_categories"
            form: "user_categories[]"
            validate: "omitempty,unique"
          x-go-type-skip-optional-pointer: true
    SubscriptionState:
      description: >
        contains properties tracking the state of the subscription.
      type: object
      required:
        - marked_read
      properties:
        marked_read:
          description: records when the subscription was last marked read.
          x-go-type: "time.Time"
          x-oapi-codegen-extra-tags:
            form: "-"
            validate: "required"
        item_states:
          description: >
            contains states of items that the user has explicitly marked or saved.
          type: array
          items:
            $ref: "#/components/schemas/ItemState"
          x-oapi-codegen-extra-tags:
            form: "-"
            validate: "omitempty,unique"
          x-go-type-skip-optional-pointer: true
        unread_count:
          description: >
            indicates how many items are unread for the subscription.
          type: integer
          minimum: 0
          x-oapi-codegen-extra-tags:
            json: "-"
            form: "-"
            validate: "numeric,gte=0"
          x-go-type-skip-optional-pointer: true
    Subscription:
      description: >
        represents a feed a user has subscribed to.
      type: object
      allOf:
        - $ref: "#/components/schemas/Timestamps"
        - $ref: "#/components/schemas/SubscriptionCustomisation"
        - $ref: "#/components/schemas/SubscriptionState"
        - type: object
          required:
            - subscription_id
            - feed_id
          properties:
            subscription_id:
              $ref: "#/components/schemas/SubscriptionID"
            feed_id:
              $ref: "#/components/schemas/FeedID"
            feed:
              description: >
                contains the Feed details. This field will be populated at query time.
              allOf:
                - $ref: "#/components/schemas/Feed"
              x-oapi-codegen-extra-tags:
                json: "-"
                form: "-"
                validate: "required"
    Feed:
      description: represents a feed object.
      type: object
      allOf:
        - $ref: "#/components/schemas/ObjectCommon"
        - type: object
          required:
            - feed_id
            - source
            - created_at
          properties:
            feed_id:
              $ref: "#/components/schemas/FeedID"
            source:
              description: >
                is a URL to the source Feed document.
              allOf:
                - $ref: "#/components/schemas/URL"
              x-go-name: SourceURL
              x-oapi-codegen-extra-tags:
                validate: "required,url"
            created_at:
              $ref: "#/components/schemas/CreatedAt"
    Item:
      description: represents an individual item (e.g., an individual feed item).
      type: object
      allOf:
        - $ref: "#/components/schemas/ObjectCommon"
        - type: object
          required:
            - item_id
            - feed_id
            - "@timestamp"
          properties:
            "@timestamp":
              $ref: "#/components/schemas/Timestamp"
            item_id:
              $ref: "#/components/schemas/ItemID"
            feed_id:
              $ref: "#/components/schemas/FeedID"
            state:
              $ref: "#/components/schemas/State"
            content:
              $ref: "../pkg/feeds/types.yaml#/components/schemas/Content"

