# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/schemas/v3.0/schema.yaml

# Copyright 2024 Joshua Rich <joshua.rich@gmail.com>.
# SPDX-License-Identifier: 	AGPL-3.0-or-later

openapi: "3.0.3"
info:
  version: 1.0.0
  title: Common Models
  description: Common objects and fields.
paths: {}
components:
  schemas:
    SchedulerID:
      description: is the unique ID of a job scheduler instance.
      type: string
      x-oapi-codegen-extra-tags:
        validate: "required"
        json: "scheduler_id"
    ScheduledJob:
      description: represents a job that has been scheduled by the job scheduler.
      type: object
      required:
        - SchedulerID
        - Schedule
        - NextRun
        - Data
        - created_at
      properties:
        created_at:
          $ref: "models.yaml#/components/schemas/CreatedAt"
        Schedule:
          type: string
          x-oapi-codegen-extra-tags:
            json: "job_trigger"
            validate: "required,cron"
          x-go-type-skip-optional-pointer: true
        NextRun:
          x-go-type: "time.Time"
          x-oapi-codegen-extra-tags:
            json: "job_next_run"
          x-go-type-skip-optional-pointer: true
        Options:
          x-go-type: "*quartz.JobDetailOptions"
          x-go-type-import:
            path: "github.com/reugn/go-quartz/quartz"
          x-oapi-codegen-extra-tags:
            json: "job_options,omitempty"
          x-go-type-skip-optional-pointer: true
        Data:
          type: object
          oneOf:
            - $ref: "#/components/schemas/FeedJob"
          x-oapi-codegen-extra-tags:
            json: "job_data"
          x-go-type-skip-optional-pointer: true
        SchedulerID:
          $ref: "#/components/schemas/SchedulerID"
    FeedJob:
      description: represents a job that fetches new items for a feed.
      type: object
      required:
        - ID
        - URL
      properties:
        ID:
          $ref: "models.yaml#/components/schemas/FeedID"
        URL:
          $ref: "models.yaml#/components/schemas/URL"
